### ISSUE TITLE
Does not show rootPage under [locale] when rewrite is enabled

### ISSUE THREAD

**Issue by aulonm** [QuiiBz/next-international#100]
Issue Description:
We are testing this library and managed to almost make it work perfectly. Love that you have added an option to not show the language in the URL, since we work with domains and not different language-paths. 

We also have a different basePath than the `/`-path. When we navigate to the root which is `localhost:3000/medlem` it wont use the files that are within `app/[locale]/page` but it uses `app/page`. Is there something that I'm doing wrong or does it not work? It should rewrite from `/basePath` to `/basePath/[locale]` but it doesn't at the moment.

Reproduction Steps:
Run the server and go to `localhost:3000/medlem` it shows the default next template code, but it should actually show the text `This is the root page with locale turned on` which is under `app/[locale]/page.tsx`. It only shows pages from `[locale]` when I'm navigating to level 2 which is `/[locale]/under` in my repro-repo linked:
https://github.com/aulonm/next-international-repro

Expected Behavior:
It should show pages that are under [locale] and not a page outside of the [locale] folder when navigating to the root of the website.

Actual Behavior:
Shows the page from the root of the app-dir

Next.js version: 13.4.13
next-international version: 0.8.1

Best regards,

**Comment by QuiiBz** [comment]
I've tried locally and this looks like an issue with the `matcher` option of the middleware. It doesn't run at all when navigating on the website (you can add a `console.log` inside the middleware to test).

I'm not sure to understand exactly how `matcher` works when having a `basePath`, but `matcher: ['/']` seems to work.

**Comment by aulonm** [comment]
oooh, the matcher! That made more sense. I'll be testing it on our production build with different matchers but it looks like it works as it should in the repro repo I linked to with a second string in the matcher-config. Doing a test with `['/']` and it looks like it works as you said.

Thank you again, Tom! 

I'll close it for the time being and I'll reopen it if I find something else that is relevant here
