### ISSUE TITLE
Examples of `international-types` seems outdated

### ISSUE THREAD

**Issue by Yovach** [QuiiBz/next-international#102]
Hello QuiiBz,

The documentation for the `international-types` library seems to be out of date as the API has changed.
The [third example](https://github.com/QuiiBz/next-international/blob/main/packages/international-types/README.md#type-safe-params) displays an error on the line `Value extends LocaleValue = ScopedValue<Locale, undefined, Key>`.

Currently, the examples show a function that receives a type where the keys are on the first level but never "scoped".
Is it possible to add an example with scoped and plural values like above ? 

```
import { BaseLocale, FlattenLocale, LocaleValue, ParamsObject, ScopedValue } from "international-types";

const translations = {
  hello: {
    "people#one": "Hello you",
    "people#other": "Hello everyone",
  },

  "coin#one": "1 coin",
  "coin#other": "{count} coins",
} as const;


type TranslationType = typeof translations;

export function translate<
  Locale extends BaseLocale,
  Key extends keyof FlattenLocale<Locale> = keyof FlattenLocale<Locale>,
  Value extends LocaleValue = ScopedValue<Locale, undefined, Key>,
>(k: Key, params: ParamsObject<Value>) {
  // ...
}

translate<TranslationType>("hello.people", { count: 5 });
```

Thanks for you library and for your great work!

**Comment by QuiiBz** [comment]
Thanks, I've updated the examples to match the new API.
