### ISSUE TITLE
Placing application code under the src directory breaks translations

### ISSUE THREAD

**Issue by mentorkadriu** [QuiiBz/next-international#104]
Based on: https://nextjs.org/docs/app/building-your-application/configuring/src-directory
We can setup our source directory as `src/app` or `src/pages`, but this breaks translations.
Is something we can do about it?

If a link has ref of `http://localhost:3000/contact` it is expected to navigate to `http://localhost:3000/en/contact` but it navigates to `http://localhost:3000/contact`, which returns 404

**Comment by QuiiBz** [comment]
Please provide a reproduction so we can debug this issue.

**Comment by QuiiBz** [comment]
Thanks, just tried and you have to move the `middleware.ts` inside the `src` directory, see https://nextjs.org/docs/app/building-your-application/routing/middleware#convention
