### ISSUE TITLE
show en or fa locale in url after add {urlMappingStrategy: 'rewrite'} to middleware

### ISSUE THREAD

**Issue by sajjadramezani73** [QuiiBz/next-international#106]
a have a project with persian and english language.

i add below code to middleware file:
const I18nMiddleware = createI18nMiddleware(['en', 'fa'] as const, 'fa', {
  urlMappingStrategy: 'rewrite',
})

after run project and after change language with switch component, en or fa show in url?

**Comment by QuiiBz** [comment]
From what I've tested, it's not easily possible to push a new route with a new locale without showing it in the URL. Feel free to send a PR if you belive this shouldn't be the case!

**Comment by sajjadramezani73** [comment]
> From what I've tested, it's not easily possible to push a new route with a new locale without showing it in the URL. Feel free to send a PR if you belive this shouldn't be the case!

https://github.com/QuiiBz/next-international#rewrite-the-url-to-hide-the-locale
In this link, it is said that locale can be removed from the url.

I used the same code.
However, this code does not work correctly and cannot remove the locale?

**Comment by QuiiBz** [comment]
This works when initially navigating to the website and switching pages, but not when changing the locale (as explained before, it's not easily doable)

**Comment by QuiiBz** [comment]
@sajjadramezani73 feel free to re-open an issue if you believe this shouldn't be the case.
