### ISSUE TITLE
Can we like pass Browser local detection and set any language as Default Locale?

### ISSUE THREAD

**Issue by sikandarchishty** [QuiiBz/next-international#108]
Is it possible to set a default locale that bypasses the default browser locale?

I always get redirected to browser default which is exactly what I want to prevent.

**Comment by QuiiBz** [comment]
This is currently not possible: next-international will try to use the user's defined locale if it has been configured in `createI18n`, or fallback if none has been found. What's the reason you don't want users to have their preferred locale?

**Comment by sikandarchishty** [comment]
Particularly in current use case I want a default language despite user's locale and then ability to change accordingly if they want.

What's the order of check list? is this the one?

1. User detected locale
2. User defined locale
3. fallback

if yes, is there a possibility to change this order and override everything to use jsut user-defined?

Thanks.

**Comment by QuiiBz** [comment]
I'm assuming you are using the App Router, so the order is:

- Extract the user's locale from the `Accept-Language` header
- If the header isn't found, use the default locale
- If the locale has been defined in the array of `createI18nMiddleware`, use it
- Else, use the default locale

The default locale is the one defined as a second argument in `createI18nMiddleware`. It's currently not possible to force the default locale, but we could add an option if necessary.

**Comment by sikandarchishty** [comment]
It would be great to add this override functionality, I have encountered this problem with every package and couldn't find the solution to this.
Is there a quicker fix that I can do on my own or wait for next release?

Thanks a ton.

**Comment by QuiiBz** [comment]
This is somehow related to https://github.com/QuiiBz/next-international/issues/96 as both issues could be solved with the same solution (= having a new option to return the locale from a request)

**Comment by QuiiBz** [comment]
I've released [0.9.0](https://github.com/QuiiBz/next-international/releases/tag/0.9.0) which includes a new `resolveLocaleFromRequest` option inside `createI18nMiddleware`, where you can add your own locale resolution logic. 

Feel free to open another issue if you're not able to make it work.
