### ISSUE TITLE
Matching locale with path name initals throws 404

### ISSUE THREAD

**Issue by sikandarchishty** [QuiiBz/next-international#109]
I've been playing around this lib for a couple days now, very easy to implement and play around. 

I just reached a scenario where if the pathname initials matches locale name we get 404:

Setup:

- I have two locales: ["ur","en"].
- I have routes set as **uru**, **eno**

Since **uru** matches the locale "ur", when switching to this page (mysite.com/uru or mysite.com/eno) I get 404 and same goes for **eno** since it matches "en", regardless of what current locale is.

here's the [Codesandbox](https://codesandbox.io/p/sandbox/purple-river-klrhdv?file=%2Fmiddleware.tsx%3A9%2C2)

The middleware is somehow confused here when rewriting urls.

Please take a look.

Thanks :)

**Comment by QuiiBz** [comment]
This isn't a bug and is the expected behavior: your URLs are `/en/uru` and `/en/eno` (or `/ur/uru` and `/ur/eno`) since all URLs are prefixed by the locale.

If you never want to show the locale in the URL, you can use the `urlMappingStrategy: 'rewrite'` option: https://github.com/QuiiBz/next-international#rewrite-the-url-to-hide-the-locale

**Comment by sikandarchishty** [comment]
I am confused on how this is an expected behavior?

If you check the Codesandbox you can clearly see the issue that it gives 404 beacuse:

path name: `uru` matches locale `ur` and `eno` with `en` which confuses the rewriting somehow

if you visit `uru` or `eno` even with the `urlMappingStrategy: 'rewrite'` still gives 404.

however other pathnames `test` works fine because its initials doesn't match locales.

Please take a look at the [sandbox](https://codesandbox.io/p/sandbox/purple-river-klrhdv)

Thanks.

**Comment by sikandarchishty** [comment]
One more thing,

- navigating to `test` adds local in url
- navigating to `uru` or `eno` removes locale from url and throws **Locale not found error**

**Comment by QuiiBz** [comment]
I did not understand what you meant in your first comment, and I did not see the links to navigate in the preview (white text on white background):

![Screenshot 2023-08-12 at 18 47 40](https://github.com/QuiiBz/next-international/assets/43268759/41d07985-d04c-4213-b0e6-9c8cf342343d)

I'll take a look tomorrow.

**Comment by QuiiBz** [comment]
I've released [0.9.1](https://github.com/QuiiBz/next-international/releases/tag/0.9.1) to fix this bug!
