### ISSUE TITLE
[ Possible Bug ] Next Images / Middleware Match Patterns

### ISSUE THREAD

**Issue by nikuscs** [QuiiBz/next-international#118]
Hey! Thanks for the amazing package at first, really clean, ts, just magic!

I was trying in a fresh project on the latest next canary, while everything looks like working at glance, it seems like images being served from **Next Images** component are having issues, because the middleware actually looks for the original url path.

So lets say you have : **"public/one.png"** , thats the actual URL that arrives at the middleware and not **"_next/images?url..."**

For me it seems like next middleware should exclude public assets by default, but there should be reason why they didnt :p

Im not sure if this an actual upstream issue, but just wanted to mention i able to replicate this on your demo repo.

My suggestion for this would be either include the matches by default on your create middleware so users have a better DX by having stuff ignored out of the box.

This seems related to https://github.com/vercel/next.js/discussions/36308#discussioncomment-3758041

The solution for me was updated the following on the middleware.ts

```ts
export const config = {
  matcher: '/((?!api|static|.*\\..*|_next).*)',
}
```

Next Version: ^13.4.17-canary.0
Router: App Router

**Comment by QuiiBz** [comment]
That looks indeed like a Next.js issue, I don't think I can do anything at the library level apart from updating the matcher regex. The middleware API will also be updated in the v1 version which should be out soon, I'll include a `I18nMiddleware.matcher` field to make it easier.

**Comment by QuiiBz** [comment]
Just checked the Next.js docs and we won't be able to provide a variable for the matcher regex, because Next.js needs it to be statically analyzable:

![Screenshot 2023-08-17 at 07 55 11](https://github.com/QuiiBz/next-international/assets/43268759/55adebd3-84e2-4479-8519-a15f239b50b5)
