### ISSUE TITLE
Invalid typing of useCurrentLocale()

### ISSUE THREAD

**Issue by roux1max** [QuiiBz/next-international#122]
Hi!

Thanks for the work here. I was just looking at the code and noticed that the `createUseCurrentLocale()` function in `src/app/client` has a return type that does not match the returned function (the `config` parameter is missing). Is it intentional?

If it is, how can we provide a custom segment name?

**Comment by QuiiBz** [comment]
Thanks, I've just released [0.9.2](https://github.com/QuiiBz/next-international/releases/tag/0.9.2) which fixes the type bug. You could already pass a config parameter but the type was wrong.

**Comment by QuiiBz** [comment]
`getStaticParams` doesn't need the segment name, as it uses directly the keys of the locales object from `createI18nServer`:

https://github.com/QuiiBz/next-international/blob/70bb097fe00c60d64231f363a47718217c5fbc4b/packages/next-international/src/app/server/create-get-static-params.ts#L3

**Comment by roux1max** [comment]
It does, the key returned by each object in the array is `'locale'`, which will match the path segment as per [NextJs documentation](https://nextjs.org/docs/app/building-your-application/routing/dynamic-routes#generating-static-params).

In order for `createGetStaticParams` to work, it would need to be changed to something like this:

```typescript
export function createGetStaticParams<Locales extends ImportedLocales>(locales: Locales) {
  return function getStaticParams(config?: I18nCurrentLocaleConfig) {
    return Object.keys(locales).map(locale => ({
      [config?.segmentName ?? DEFAULT_SEGMENT_NAME]: locale,
    }));
  };
}
```

**Comment by QuiiBz** [comment]
Oh I understand what you mean now, sorry. I'll make another fix for it.
