### ISSUE TITLE
Missing license info at npmjs.com

### ISSUE THREAD

**Issue by noxify** [QuiiBz/next-international#129]
Hi,

while running `pnpm licenses ls` i mentioned that your packages haven't a license info in the npm registry.

* https://www.npmjs.com/package/next-international
* https://www.npmjs.com/package/international-types

The current output is:

```
├──────────────────────────────────────────┼─────────────────────────────────────┤
│ international-types                      │ Unknown                             │
├──────────────────────────────────────────┼─────────────────────────────────────┤
│ next-international                       │ Unknown                             │
└──────────────────────────────────────────┴─────────────────────────────────────┘

```

Would be good if the license info at npmjs could match the specified license ( `MIT` )

Thanks!

**Comment by QuiiBz** [comment]
Great suggestion, thanks! Will be included in the next release.
