### ISSUE TITLE
Pages-dir and App-dir can't work together

### ISSUE THREAD

**Issue by aulonm** [QuiiBz/next-international#133]
Hi,

Thanks for the amazing DX on next-international, and all the help you have been providing!

We are in a middle of a migration from pages to app-dir and need them both to colocate since its a fairly big application and it takes time to migrate 100% over to app-dir.

The repro: https://github.com/aulonm/next-international-repro (updated it with this issue)

The problem we are facing now is when we add `[locale]` folder to the `app`-folder, and `next.config` has the `i18n`-object (this is needed for pages-dir). 

The routing doesn't work as expected. 

App-dir has the following routes:
- /
- /client
- /subpage

Pages dir has the following routes:
- /ssr-ssg

When running the dev-server and navigating to /ssr-ssg it returns the pages-dir, which is correct.
When navigating to /client it returns the root-file in app-dir and I can't get access to the subpages withouth doing something like `/en/subpage` or `/en/client` (the client one doesn't work).

Is this a limitation in the package or something that I'm missing?

**Comment by QuiiBz** [comment]
That might be related to https://github.com/vercel/next.js/issues/47430 - removing the `i18n` config inside `next.config.js` resolves the issue for the App dir, but (as expected) breaks the Pages Dir.

**Comment by aulonm** [comment]
If I read that issue correct, shouldn't next-international change to check the `request.url.pathname` and not `request.nextUrl.pathname` for the `locale` or would that be the wrong way fo doing this?
