### ISSUE TITLE
Best practice for localizing within a config file

### ISSUE THREAD

**Issue by zackrw** [QuiiBz/next-international#139]
Out of the box my code has a configuration file
```ts
export const siteConfig = {
  name: "My website",
}
```

And then in the React component it has something like
```tsx
import { siteConfig } from '...'

export default async function Page() {
  return (
    <h1>{siteConfig.name}</h1>
  )
}
```

All else equal, I would like to have my string ID just be the strings themselves, for readability in a simple project. So ideally it would be something like:

```ts
import { getI18n } from '@/locales/server' 

const t = await getI18n() // Wouldn't work because it's outside of a function

export const siteConfig = {
  name: t('My website'),
}
```

... and/or ...

```tsx
import { siteConfig } from '...'
import { getI18n } from '@/locales/server'

export default async function Page() {
  const t = await getI18n()
  return (
    <h1>{t(siteConfig.name)}</h1>
  )
}
```

This may be a niche question, but Is there recommended best practice for this, or do I have to settle for including the string ID itself in the component? That solution would look like:

```tsx
import { siteConfig } from '...'
import { getI18n } from '@/locales/server'

export default async function Page() {
  const t = await getI18n()
  return (
    <h1>{t('My website')}</h1>
  )
}
```

The main reason this is not desirable is that the config file is used in multiple components. With the strings themselves as IDs, then it's harder to remember and standardize this way. (Although with an ID like site_title it would not be a problem.)

Thanks for your help!

**Comment by zackrw** [comment]
I've worked on this a bit more and the function approach only works when importing to server components:

<img width="532" alt="Captura de pantalla 2023-09-13 a la(s) 7 42 39 p m" src="https://github.com/QuiiBz/next-international/assets/954970/6304bf16-133a-4ed0-9b61-8205a7644eb0">

This fails when you reference them within a client component

<img width="817" alt="Captura de pantalla 2023-09-13 a la(s) 7 42 58 p m" src="https://github.com/QuiiBz/next-international/assets/954970/902ab862-6209-405a-929b-130b3e68933e">

The obvious alternative of useI18n isn't a good solution because that's meant for react components
<img width="960" alt="Captura de pantalla 2023-09-13 a la(s) 7 42 02 p m" src="https://github.com/QuiiBz/next-international/assets/954970/fd884461-f76d-4660-bac2-a69470d41b97">

I'm not sure if this is addressed in 1.0, but I think it's important because this is a common pattern for NextJS, e.g. https://github.com/shadcn-ui/ui/tree/main/apps/www/config

Just looking at NextJS docs, it could be simplest to write a quick importer and then pass in the locale from the generate function (https://nextjs.org/docs/app/building-your-application/routing/internationalization).

So like `generateSiteConfig('en')` and then load that dictionary dynamically in config/site.ts ... I'm not sure about the performance implications off-hand, if there would be any. It's not super elegant though.

**Comment by zackrw** [comment]
One other approach I've considered is calling t() on the variable in the component instead of the config file. So you just leave the config file as is and then in your component do:

```ts
{t(siteConfig.title)}
```

The main issue (feature not a bug!) is type checking doesn't like that, and (less important) it's marginally harder to keep track of which strings you are localizing.

**Comment by zackrw** [comment]
I ended up with a not-so-good solution that works but I believe loads 4x more data than it should. Any ideas how to make it work better?

What I've done is make a new file that can be imported everywhere:
```ts
import en from './en.json'
import pt_BR from './pt-BR.json'
import es from './es.json'
import fr from './fr.json'

const locales = {
  'en': en,
  'pt-BR': pt_BR,
  'es': es,
  'fr': fr
}

export const getDictionary = (locale: string) => {
  const dictionary = locales[locale]
  return (str: string) => {
    return dictionary[str]
  }
}
```
And then calling getDictionary to create the t function inside another function that takes a locale parameter

```ts
import { getDictionary } from '@/yuzu/hybrid'

export const generateSiteConfig = (locale: string) => {
  const t = getDictionary(locale)

  return {
    name: "Supervideos",
    description:
      t("Create fully edited videos in seconds!"),
    url: "https://supervideos.app",
    ogImage: "https://supervideos.app/og.jpg",
    links: {
      twitter: "https://twitter.com/supervideosapp",
      github: "https://github.com/xdaluca",
    },
  }
}
```

Then using in a server environment:

```ts
export const generateMetadata = async () => {
  const locale = getCurrentLocale()
  const siteConfig = generateSiteConfig(locale)
  const t = await getI18n()

  return {
    title: {
      default: siteConfig.name,
      template: `%s | ${siteConfig.name}`,
    },
    description: siteConfig.description,
    keywords: [
      t("Video Creation"),
      t("AI generated"),
      t("Editing tool"),
      t("Marketing Videos"),
      t("Make videos"),
    ],
    authors: [
      {
        name: "supervideos",
        url: "https://supervideos.app",
      },
    ],
...
``` 

Or a client one:

```ts
export async function MobileNav({ items, children }: MobileNavProps) {
  useLockBody()

  const locale = useCurrentLocale()
  const siteConfig = generateSiteConfig(locale)

  return (
    <div
      className={cn(
        "fixed inset-0 top-16 z-50 grid h-[calc(100vh-4rem)] grid-flow-row auto-rows-max overflow-auto p-6 pb-32 shadow-md animate-in slide-in-from-bottom-80 md:hidden"
      )}
    >
      <div className="relative z-20 grid gap-6 rounded-md bg-popover p-4 text-popover-foreground shadow-md">
        <Link href="/" className="flex items-center space-x-2">
          <Icons.logo />
          <span className="font-bold">{siteConfig.name}</span>
        </Link>
...
```

**Comment by zackrw** [comment]
It's also worth noting that this simple implementation doesn't support plurals.

**Comment by QuiiBz** [comment]
The main issue in your solution is (as you mentioned) that you're loading too much data. Probably not an issue when used on the server, but should be avoided on the client:

```ts
// All locales are loaded immediately because of this
const locales = {
  'en': en,
  'pt-BR': pt_BR,
  'es': es,
  'fr': fr
}
```

You can try to replace these values with dynamic imports, similar to `createI18n*`:

```ts
const locales = {
  'en': () => import('./en.json'),
  'pt-BR': () => import('./pt-BR.json'),
  'es': () => import('./es.json'),
  'fr': () => import('./fr.json'),
}

export const getDictionary = async (locale: string) => {
  const dictionary = await (locales[locale])()
  return (str: string) => {
    return dictionary[str]
  }
}
```

On the server, you can then `await getDictionary(locale)`, and on the client `use(getDictionary(locale))`.

Just to make I sure understand correctly your pain point, do you wish to be able to use `getI18n` inside `generateMetadata`, or be able to split locales in multiple files and use `getI18n` with it?

**Comment by zackrw** [comment]
My goal is the first one: using getI18n inside generateMetadata, which may be called on the client or the server. The goal is simply to be able to have one config file instead of server + client.

**Comment by zackrw** [comment]
The challenge with what you suggested is that I'm calling getDictionary inside a file that needs to work on server and client, so at that point I don't know if I'll be `await`ing or `use`ing. 

It feels like I either need to hardcode the string key into the server and client files (meaning it's duplicated) OR call `t()` on a variable, which violates type assumptions and also make related tasks like extraction more difficult (but not impossible).

**Comment by QuiiBz** [comment]
> The goal is simply to be able to have one config file instead of server + client

Not sure to understand correctly this part. Are you referring to the options passed to `createI18nClient` & `createI18nServer`?

**Comment by zackrw** [comment]
Sorry for not being more clear. I'm referring to the config file in my app prior to doing localization.

For example, here ui.shadcn.com config directory, where for example in site.ts, `siteConfig.description` is defined as `'Beautifully designed components built with Radix UI and Tailwind CSS.'`

https://github.com/shadcn-ui/ui/tree/c21ecfb665214e18cd5914ea319f925cd676e786/apps/www/config

Since that is where the raw string lives, it is desirable to call the `t()` function there. I am using the string itself as the i18n key, by the way.

--

Then it is included in two different files (but often many more in more complex projects):

https://github.com/search?q=repo%3Ashadcn-ui%2Fui+siteConfig.description&type=code

If one of those files were a client file and the other were server, it would complain because the `t()` function called in the site.ts file would not be able to run on both client and server.

**Comment by xdaluca** [comment]
I've got a bunch of strings in config files and still getting errors, is there any development on this?

**Comment by zackrw** [comment]
My latest approach here is to just use server-side tools (e.g. getI18n) and then to pass the config object as a prop into any client components that need it. 

@QuiiBz I'm curious if this sounds like a practice worth recommending?

**Comment by QuiiBz** [comment]
> hey there 👋🏼 I've got a bunch of strings in config files and still getting errors, is there any development on this?

Maybe these strings don't have the correct type? They should be narrowed down to match a key (usually with `as const`), so instead of their type being `string`, it should be `"a.key"`.

We don't have any recommendations as it's highly dependent on each existing setup. Trying to make something generic would probably not work for everyone.

> I'm curious if this sounds like a practice worth recommending?
This seems absolutely fine to me.

**Comment by QuiiBz** [comment]
Closing as the original question seems resolved, feel free to re-open an issue if you have more questions on this topic!
