### ISSUE TITLE
Fallback values on server

### ISSUE THREAD

**Issue by Vahor** [QuiiBz/next-international#141]
Hi!

We are in the process of translating our website, so currently not everything is translated. 
With the I18nProvider (client-side), that's not an issue.
However, with the server methods, there is no fallback available, and it returns the translation key.

From what I see in [createGetI18n](https://github.com/QuiiBz/next-international/blob/main/packages/next-international/src/app/server/create-get-i18n.ts#L14) and [createGetScopedI18n](https://github.com/QuiiBz/next-international/blob/main/packages/next-international/src/app/server/create-get-scoped-i18n.ts#L14), the `fallbackLocale` is set to undefined.
Is there a reason to that ? Or am I missing something ?

I made a [simple test on my end](https://github.com/Vahor/next-international/commit/07554345f59503e11c7d1243137538f8aaf3b526) and passing a fallbackLocale directly in those like this, and it seemed to work.

We pass the parameters like this:
```ts
import { createI18nServer } from "next-international/server";

export const { getI18n, getScopedI18n, getStaticParams } = createI18nServer(
  {
    en: () => import("./en"),
    fr: () => import("./fr"),
  },
  {
    fallbackLocale: "fr",
  }
);
```

**Comment by QuiiBz** [comment]
I think this is indeed something that we forgot to add. For the [1.0.0 release](https://github.com/QuiiBz/next-international/pull/126), the API has been updated to provide more flexibility and thus will contain options as the second argument to `createI18n*` just like you did.

I'm planning to release soon v1.0.0, so I think it's a good idea to release this feature along it (instead of updating the API just before a major)

**Comment by QuiiBz** [comment]
I've published [1.0.0-rc.0](https://www.npmjs.com/package/next-international/v/1.0.0-rc.0) as a release candidate of the v1 release if you want to try this feature.

This release brings some breaking changes, you can see the upcoming changelog in the PR description: https://github.com/QuiiBz/next-international/pull/126

**Comment by AvaN0x** [comment]
It's working fine with the release candidate, ty :)

**Comment by QuiiBz** [comment]
Thanks for trying it out! Closing this issue as v1 will be released in the coming days/weeks.
