### ISSUE TITLE
Infinite redirect loop using `urlMappingStrategy: rewrite`

### ISSUE THREAD

**Issue by vntw** [QuiiBz/next-international#143]
Hey there,

thanks for the library, I'm excited to see where this is heading in the future 🙂

When testing this library I pretty much instantly encountered an infinite redirect loop (Chrome/FF) using `urlMappingStrategy: rewrite`. I saw #96 but I'm not sure if these are related, the `resolveLocaleFromRequest` function didn't make a difference, sorry if it's a duplicate.

I forked the codesandbox from the docs page: https://codesandbox.io/p/sandbox/recursing-yonath-973rl3?file=/middleware.ts:6,5-6,29 and changed the strategy option parameter.

The loop happens after clicking a locale button or switching the locale in the URL manually

<img width="733" alt="image" src="https://github.com/QuiiBz/next-international/assets/502368/65311a21-4495-4160-b444-0d74eced3cad">

---

**Unrelated** but since I'm here: Do you see hiding the default locale from the URL as a valid feature request for this library? I've seen this as a popular URL strategy also used by other i18n libraries. If yes I can create an issue for it!

**Comment by QuiiBz** [comment]
Thanks for the kind words. Can you try running the same locally? I believe CodeSandbox has issues with cookies, so that might be why you're getting this infinite redirection.

**Comment by vntw** [comment]
Oh you beat me to it, but thank you! Yes I can confirm it's also happening locally. I tried out the lib in a new project but didn't get far. After that I also tried the `next-app` example from this repo with the same result 🙂

**Comment by QuiiBz** [comment]
I've published https://github.com/QuiiBz/next-international/releases/tag/0.9.5 which includes #146 and should fix the issue (sorry for the bad first impression of this library). Feel free to open another one if that's not the case!
