### ISSUE TITLE
Regression with new "Fallback Locale API" (client components)

### ISSUE THREAD

**Issue by Yovach** [QuiiBz/next-international#149]
Hi,

I'm currently trying out the "next-international@1.0.0-rc.3" version but I'm experiencing a small problem that didn't exist before.

Previously, we could throw the object containing the translations into the "fallbackLocale" and then when we used "useI18n", we had these values by default, so it avoided having short texts like "about.you".

The client now loads the "fallback" language values after rendering :/

You can reproduce by cloning https://github.com/yovach/next-international/tree/issue-with-no-fallback or with the following layout : 

```typescript
// layout.tsx
'use client';

import { ReactNode } from 'react';
import { I18nProviderClient } from '../../../locales/client';

export default function Layout({ children }: { children: ReactNode }) {
  return <I18nProviderClient fallbackLocale="en">{children}</I18nProviderClient>;
}
```

**Comment by QuiiBz** [comment]
If you don't want to show the translation keys while the locale files are loading, you can use the `fallback` prop from `I18nProviderClient` that accepts a `ReactElement`. Would that solve your issue?

**Comment by Yovach** [comment]
It doesn't really solve my problem because it was a nice feature of pre-1.0.

Wouldn't there be a way to preload the languages and send them to the client as before? If it's too much work, I could just stick with the current behavior and make some changes to my interface.

**Comment by QuiiBz** [comment]
I changed my mind and I think you're right. The new API is better for DX, but worse for UX (but it's the most important thing). I've reverted the changes to allow back passing a locale object to `fallbackLocale`, instead of lazy-loading it. See #150 and https://www.npmjs.com/package/next-international/v/1.0.0-rc.4
