### ISSUE TITLE
Lot of potential but too strongly bounded by nextjs.

### ISSUE THREAD

**Issue by akashraj9828** [QuiiBz/next-international#15]
I want to use it in a react native project but just because it's using `GetStaticProps` and `Router` from `next` hence it can't be used anywhere except the `next js` project.

I see a lot of potential in this library if it was not strongly bounded to one library. This can easily work in any react based project.

U can provide optional "no configuration" and "automatic binding" for the next js as an extension for this library.

Thoughts?

**Comment by QuiiBz** [comment]
There are a few reasons why this library currently only works with Next.js:

- `getStaticProps` allows to serve content in multiple languages while having good Web Vitals and SEO, although I think crawlers can execute JavaScript and so load the right locale client-side; but that means higher Cumulative Layout Shift / First Input Delay.
- Next.js already offers a very good i18n routing with almost no configuration, and this library uses the same configuration to make developers' life easier.

I've been already thinking about how this could be ported to be framework agnostic, but that's kinda hard to achieve right now. We'll have to split the library into a "core" package, then another package for each framework to allow SSR / plug to the framework's i18n routing (and what happens if a framework doesn't provide i18n routing?). That's definitely something I want to implement in the future.

**Comment by akashraj9828** [comment]
I feel like the core functionality that is providing a `type-safe utility to manage language bundles in react project` can be easily extracted and quickly made framework agnostic by just exposing the `useI18n` hook independently and exposing some functions from inside it like `changeLocale`

I did use some of your types to extend the `https://www.npmjs.com/package/i18n-js/v/next` library to introduce strict type checking and extracting parameters out of strings (awesome work on that thou 🎉). 

I'm glad u were thinking of making this framework agnostic anyways good luck on that.

Keeping this thread open for now. If you ever work on this feature. Feel free to update this thread for others to follow.

**Comment by QuiiBz** [comment]
Agree that `I18nProvider` & `useI18n` can be easily extracted into a standalone package. But one of the goals of this library is to have everything ready-to-go, with minimal/no extra configuration. I'll update the issue when we start working on making `next-international` framework agnostic!

**Comment by maximkott** [comment]
I believe the idea behind this package is really nice, and thanks to your trick for parameter extraction I was able to fill in the gaps for my own implementation. 

I'd highly suggest separating the types, helpers, etc. into a separate package and build next-international on top of it. This way people would be able to use your ts magic in a standalone way.

Below I'm sharing some types that I wrote for my own needs, as an experiment, you might find it useful. I've learned parameter extraction from your library - thanks for that!

```typescript
type Source = Record<SourceKey, any>
type SourceKey = string | number

type InferKeys<TSource extends Source> = Exclude<
  Extract<keyof TSource, SourceKey>,
  keyof any[]
>

type InferNestedKeys<
  TSource extends Source,
  TKey extends SourceKey = InferKeys<TSource>
> = TKey extends SourceKey
  ? TSource[TKey] extends Source
    ? `${TKey}` | `${TKey}.${InferNestedKeys<TSource[TKey]>}`
    : `${TKey}`
  : `${TKey}`

type InferValue<
  TSource extends Source,
  TKey extends InferNestedKeys<TSource>
> = TKey extends InferKeys<TSource>
  ? TSource[TKey]
  : TKey extends `${infer TFirst}.${infer TRest}`
  ? TRest extends InferNestedKeys<TSource[TFirst]>
    ? InferValue<TSource[TFirst], TRest>
    : never
  : never

type InferPlaceholderNames<TValue> = TValue extends string
  ? TValue extends ""
    ? []
    : TValue extends `${infer TStart}{${infer TPlaceholder}}${infer TRest}`
    ? [TPlaceholder, ...InferPlaceholderNames<TRest>]
    : []
  : []

type InferPlaceholders<
  TValue,
  TReplacement = string | number | boolean | symbol
> = Record<InferPlaceholderNames<TValue>[number], TReplacement>

const get = <
  TSource extends Source,
  TKey extends InferNestedKeys<TSource>,
  TPlaceholderNames = InferPlaceholderNames<InferValue<TSource, TKey>>
>(
  source: TSource,
  path: TKey,
  ...placeholders: TPlaceholderNames extends any[]
    ? TPlaceholderNames["length"] extends 0
      ? []
      : [InferPlaceholders<InferValue<TSource, TKey>>]
    : []
): InferValue<TSource, TKey> => {
  const parts = path.split(".")

  let result: any = source

  for (let i = 0; i < parts.length; i++) {
    result = result[parts[i]]

    if (result === undefined && i === parts.length - 1) {
      throw new Error(`Property "${path}" does not exist`)
    }
  }

  const replacements = placeholders[0]

  if (replacements) {
    Object.entries(replacements).map(([key, value]) =>
      result.toString().replace(`{${key}}`, (value as any).toString())
    )
  }

  return result
}

////////////////////////////////////////////////////////////////////////////////

const source1 = {
  foo: "bar",
  yolo: { swag: "yes" },
  img: [{ foo: "baz {p}" }],
  x: 2,
} as const

type root1 = InferKeys<typeof source1>
type keys1 = InferNestedKeys<typeof source1>
type value11 = InferValue<typeof source1, "img.0.foo">
type value12 = InferValue<typeof source1, "yolo.swag">
type placeholder11 = InferPlaceholderNames<value11>
type placeholder12 = InferPlaceholders<value11>

const source2 = [
  {
    foo: "bar",
    yolo: { swag: "yes" },
    img: [{ foo: "baz {p}" }],
    x: 2,
  },
] as const

type root2 = InferKeys<typeof source2>
type keys2 = InferNestedKeys<typeof source2>
type value21 = InferValue<typeof source2, "0.foo">
type value22 = InferValue<typeof source2, "0.img.0.foo">
type placeholder21 = InferPlaceholderNames<value22>
type placeholder22 = InferPlaceholders<value22>

type names = InferPlaceholderNames<"foo {bar} baz">
type placeholders = InferPlaceholders<"foo {bar} baz {yolo}">

console.log(get(source1, "img.0.foo", { p: "y" }))
console.log(get(source1, "yolo"))
```

**Comment by QuiiBz** [comment]
Thanks for the kind words!

Yeah, splitting the types into a separate package is something that I want to do, so anyone can use them with the library they want. I think this will be part of the 1.0.0 version, along with multiple "adapters" for each React framework. Non-react frameworks are outside of the scope of this library, which strictly focuses on low-configuration and uses framework features to enhance users' experience.

**Comment by QuiiBz** [comment]
Started working on a type-specific package:

- https://github.com/QuiiBz/next-international/pull/20

**Comment by QuiiBz** [comment]
Closing this issue as stale, feel free to re-open if needed.
