### ISSUE TITLE
[Question] Is there any generic type for scopedT('something') ?

### ISSUE THREAD

**Issue by gustaveWPM** [QuiiBz/next-international#152]
Hello!

I would like to know something about the typing of the lib.

Let's assume I have a "Locale" path like: `blog-categories.lol`
If I do:

```ts
const scopedT = await getScopedI18n('blog-categories');
```

And then want to pass `scopedT` as an argument to an another function:
```ts
function dummyFunction(passedScopedT: _) {
  return scopedT('lol');
}
```

How can I type `passedScopedT`?
Is there any generic type provided by the lib, which I could use like `ScopedTGeneric<'blog-categories'>` to write:

```ts
function dummyFunction(passedScopedT: ScopedTGeneric<'blog-categories'>) {
  return passedScopedT('lol');
}

const scopedT = await getScopedI18n('blog-categories');
// meaning: const scopedT = await getScopedI18n('blog-categories') as ScopedTGeneric<'blog-categories'>;
const lolilol = dummyFunction(scopedT);
```

I'm terribly sorry to ask (this may sound like a lazy move), but I'm getting such brain aches right now that I'd really appreciate that little helping hand.

By the way, just as an aside: thank you so much for this lib. So far I've found it absolutely brilliant, and I think that without it, it would simply be impossible to write what I'm currently programming.

I'd be delighted if we could have a chat about it (on LinkedIn, for example).

I haven't finished what I'm trying to do yet, but once I do, I'd really like to have a chat about it.
Regards.

**Comment by gustaveWPM** [comment]
I've edited my issue. It was terribly badly written.
Thanks in advance for the reply!

**Comment by QuiiBz** [comment]
Not a dumb question at all! The easiest would be to retrieve the return type of `getScopedI18n`, remove the `Promise<?>` and pass the correct scope, so in your case (assuming you have a locale key `blog-categories.lol`):

```ts
function dummyFunction(passedScopedT: Awaited<ReturnType<typeof getScopedI18n<'blog-categories'>>>) {
  return scopedT('lol');
}
```

Thanks for the kind words and happy to hear that you enjoy this library! I'm doing open source thanks to folks like you. You can find my socials including Linkedin on my [personal website](https://tom.lnrd.fr).

**Comment by gustaveWPM** [comment]
Omg, thank you!
I think it would be a good idea to provide a generic type based on `Awaited<ReturnType<typeof getScopedI18n<'key'>>>`

**Comment by QuiiBz** [comment]
I'm not sure if providing a utility type for something that not everyone will need is useful as it would increase the API surface (and I don't want it to be more complex).

If someone using next-international is looking for this feature, you can copy/paste the following in your project:

```ts
import type { Scopes } from 'international-types'
import type en from './locales/en.ts'

type ScopedFn<Scope extends Scopes<typeof en>> = Awaited<ReturnType<typeof getScopedI18n<Scope>>>

function dummyFunction(scopedT: ScopedFn<'blog-categories'>) {
  return scopedT('lol');
}
```

Note that you'll need to install the `international-types` package in your project too.
