### ISSUE TITLE
[Question] Dynamic vocab retrieve?

### ISSUE THREAD

**Issue by gustaveWPM** [QuiiBz/next-international#154]
Hello!

I have some types, defining my blog sections and their sub-categories:

```ts
type BlogArchitecture = {
  'features': 'dashboard' | 'bake-a-cake';
  'getting-started': 'installation' | 'hello-world';
};

export type BlogCategory = keyof BlogArchitecture;

type BlogSubCategoriesMappedToBlogCategory = {
  [K in BlogCategory]: BlogArchitecture[K];
};

// * ... Not brilliant at all

type BlogSubCategories<K extends BlogCategory> = BlogSubCategoriesMappedToBlogCategory[K];

export type BlogCategoryAndSubcategoriesPair<C extends BlogCategory> = {
  category: C;
  subCategory: BlogSubCategories<C>;
};
```

My _locale_ schema is:
```ts
export default {
  'blog-categories': {
    'features': {
      _title: 'Features',
      dashboard: 'Dashboard',
      'bake-a-cake': 'Bake a cake'
    },
    'getting-started': {
      _title: 'Getting started',
      installation: 'Install me',
      'hello-world': 'Another subcategory title'
    }
  },
} as const;
```

And I would like to do something like:
```ts
async function dynamicRetrieve<C extends BlogCategory>({ category, subCategory }: BlogCategoryAndSubcategoriesPair<C>) {
  const globalT = await getServerSideI18n();
  const a = globalT('blog-categories.patch-notes-bis.dashboard');
  const b = globalT(`blog-categories.${category}.${subCategory}`);
}
```

But I obviously have an error:

> Type error: No overload matches this call.
  Overload 1 of 2, '(key: "navbar.patch-notes" | "navbar.dashboard" | "navbar.home" | "navbar.assistance" | "navbar.bake-a-cake" | "navbar.login" | "dashboard.base-page" | "dashboard.foo-page" | ... 12 more ... | "ugly.logo"): string', gave the following error.
    Argument of type '`blog-categories.${C}.${BlogSubCategories<C>}`' is not assignable to parameter of type '"navbar.patch-notes" | "navbar.dashboard" | "navbar.home" | "navbar.assistance" | "navbar.bake-a-cake" | "navbar.login" | "dashboard.base-page" | "dashboard.foo-page" | ... 12 more ... | "ugly.logo"'.

Would you have any idea about how I could solve it?

I'm not very good at typing, sorry. :x

Btw: let's assume I have done all the required checks to be sure that `category.subcategory` is a valid combination, that _should_ be in the `'blog-categories'` object in my _locale_ file. So we could, maybe, abuse of `as`? I would like this function to raise a type error if it is not the case, specifically on `blog-categories.${category}.${subCategory}`.

**Comment by gustaveWPM** [comment]
I don't understand why GitHub's form for writing an issue is so awful...
I have words that had disappeared between several edits of my message, very annoying. :/

Sorry, it's ok now.

**Comment by QuiiBz** [comment]
That's not something that TypeScript can achieve, because you have multiple patterns that don't match:

Category can be `features` or `getting-started`, but their sub-categories are respectively different (`dashboard` and `bake-a-cake`, `installation` and `hello-world`) so TypeScript can't narrow down the proper type for sub-categories.

You'll either have to align the sub-categories' names, or manually cast them.

**Comment by gustaveWPM** [comment]
> That's not something that TypeScript can achieve, because you have multiple patterns that don't match:

That's what I was afraid of. :(
