### ISSUE TITLE
Next.js global error page

### ISSUE THREAD

**Issue by o-az** [QuiiBz/next-international#155]
I tried to set this up but it never shows the error page:

https://nextjs.org/docs/app/api-reference/file-conventions/error#global-errorjs

I also tried `error.tsx` inside `src/app/[locale]/client` and inside `src/app/[locale]`, none are showing up

Tried all these, none show up: 

![CleanShot 2023-09-05 at 12 45 53@2x](https://github.com/QuiiBz/next-international/assets/23618431/ccf11ea8-eccf-4df7-86af-ffc97b01c3ae)

**Comment by QuiiBz** [comment]
Can you send a reproduction link? How are you triggering errors to render `error.tsx` / `global-error.tsx`?

**Comment by QuiiBz** [comment]
Closing as no reproduction has been provided. Feel free to re-open if needed!
