### ISSUE TITLE
`urlMappingStrategy` missing `rewriteDefault` option

### ISSUE THREAD

**Issue by o-az** [QuiiBz/next-international#156]
https://github.com/QuiiBz/next-international/blob/040728a29fee89869e4cf9b2699f30a27e76741a/packages/next-international/src/types.ts#L55

https://next-international.vercel.app/docs/app-middleware-configuration#rewrite-the-url-to-hide-the-locale

**Comment by QuiiBz** [comment]
You're looking at the documentation for the v1 version, which hasn't been released yet. See the release notes in the PR here:
- https://github.com/QuiiBz/next-international/pull/126

**Comment by QuiiBz** [comment]
I've just published [1.0.0-rc.5](https://www.npmjs.com/package/next-international/v/1.0.0-rc.5) that includes this new `rewriteDefault` strategy, if you already want to upgrade and test it.
