### ISSUE TITLE
How to show the right locale on client component instantly? 

### ISSUE THREAD

**Issue by ariannargesi** [QuiiBz/next-international#158]
Hey
I want to show the right locale in client component instantly? 
In server components, Things work as I want. But not in client components. In client component when i use ```useI18n``` hook, I the right locale, takes a few seconds to load. and I don't want this loading. 
Any idea how can I achieve instant loading in client component?

**Comment by QuiiBz** [comment]
Hi, what do you mean by "takes a few seconds to load"? `useCurrentLocale` is synchronous and doesn't have any delay. You can also use a `fallback` prop on `I18nProviderClient` to show a custom loading state, or use the `fallbackLocale` prop to have a default locale to render, without any loading state.

**Comment by ariannargesi** [comment]
[Screencast from 23-09-09 15:36:52.webm](https://github.com/QuiiBz/next-international/assets/46089900/b7908001-a14a-4cf4-aa78-b3dcd1cde183)

See how it shows the key from locale/fr.ts file first and then shows the value? Is is a client component which uses useI18n hook.

**Comment by QuiiBz** [comment]
As I said above, you can use the `fallbackLocale` prop to immediately render a locale without waiting for it to load.

**Comment by ariannargesi** [comment]
Um, I can't pass a string to `fallbackLocale` prop on I18ProviderClient. Typescript moan with this 
`Type 'string' is not assignable to type 'Record<string, unknown>'`

**Comment by QuiiBz** [comment]
You have to manually import the locale (and not only pass a string), see the example here:

https://github.com/QuiiBz/next-international/blob/82b12a0487291bd21f81ce8071915c2bc0f27c9e/examples/next-app/app/%5Blocale%5D/client/layout.tsx#L9

**Comment by ariannargesi** [comment]
Thanks. Is it there anyway to dynamically load the fallbackLocale based on `params.locale`?

**Comment by QuiiBz** [comment]
Dynamically loading the right `fallbackLocale` doesn't really make any sense, because of the "dynamic" part: you'll still have to wait and show some loading state on the client, precisely because it's dynamic.

You can maybe try to remove the `import()` statements in `createI18n`, but that means all locales will be loaded by the client, even if not used:

```ts
import en from './en'
import fr from './fr'

createI18n({
  en: () => en,
  fr: () => fr
})
```

Feel free to open another issue if needed!
