### ISSUE TITLE
Using `headers` function forces dynamic rendering in `getI18n()`

### ISSUE THREAD

**Issue by clopos-kamran** [QuiiBz/next-international#160]
**Describe the bug**
I want to be able to use server generated static pages using app router. But when I use `getI18n()` in components it switches to dynamic rendering because of this rule

> headers() is a [Dynamic Function](https://nextjs.org/docs/app/building-your-application/rendering/server-components#server-rendering-strategies#dynamic-functions) whose returned values cannot be known ahead of time. Using it in a layout or page will opt a route into [dynamic rendering](https://nextjs.org/docs/app/building-your-application/rendering/server-components#dynamic-rendering) at request time.

**To Reproduce**
Follow the instructions in [here](https://github.com/QuiiBz/next-international#readme)

**Expected behavior**
It should immediately return from cache. If I export my own getI18n() function and return translations for only one language it loads very fast which indicates that dynamic rendering is not turned on.

**About (please complete the following information):**
 - next-international version [e.g. 0.9.3]
 - Next.js version [e.g. 13.4.13]

**Comment by QuiiBz** [comment]
Static Rendering will be released very soon as part of the v1 release:
- https://github.com/QuiiBz/next-international/pull/126

You can already update by installing `next-international@1.0.0-rc.6` and following the upgrade guide in the above PR.
