### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by reverseSosa** [QuiiBz/next-international#161]
Can I wrap the entire application using i18nProviderClient without losing server-side rendering?

**Comment by QuiiBz** [comment]
Yes, you can do the same as [here for example](https://github.com/typehero/typehero/blob/0d752c92426919e5ca629b67a98b72fbec4885df/apps/web/src/app/providers.tsx#L19), by moving `I18nProviderClient` to a `use client` file, with a `children` prop and then use this Client Component in any Server Component.
