### ISSUE TITLE
Bug is Switching locale from page name which matches locale

### ISSUE THREAD

**Issue by sikandarchishty** [QuiiBz/next-international#162]
**Describe the bug**
Relates to [109](https://github.com/QuiiBz/next-international/issues/109), when switching locale from a specific page it does not set the locale but changes when done in reverse (let me explain :-P).

- I have two locales, `ur` as default and `en` as secondary.
- Let's say I have a page named `urban` (notice urban matches `ur` locale, [109](https://github.com/QuiiBz/next-international/issues/109)). When I am on this page and I switch to `en` locale, it switches perfectly, whereas when on this `urban` page I switch from `ur` to `en` it does not redirect/rewrite or change, its just unresponsive, the `Next-Locale` cookie doesn't change either.
- I have tried with both `urlMappingStrategy: "rewrite"` and `urlMappingStrategy: "redirect"`

**To Reproduce**
[Codesandbox](https://codesandbox.io/p/sandbox/purple-river-klrhdv)

**Expected behavior**
It should switch regardless of matching locale initials or not.

**About (please complete the following information):**
 - next-international version [e.g. 0.9.5]
 - Next.js version [e.g. 13.4.13]

**Comment by QuiiBz** [comment]
That's strange because the `eno` page seems to work correctly when updating the locale. I suspect this is related to the default locale (passed as second argument in `createI18nMiddleware`)

**Comment by QuiiBz** [comment]
I've fixed the issue in #164 and it will be part of the 1.0.0 release (#126) that will be released later today.
