### ISSUE TITLE
Erroneous logging of "Locale not found" on the server

### ISSUE THREAD

**Issue by zackrw** [QuiiBz/next-international#163]
**Describe the bug**
My console has a log for each page load that looks like this. Everything else works.

```
error - node_modules/.pnpm/next-international@0.9.5/node_modules/next-international/dist/app/client/index.js (219:0) @ eval
error - Error: Locale not found
```

I notice that this is only logged in https://github.com/QuiiBz/next-international/blob/82b12a0487291bd21f81ce8071915c2bc0f27c9e/packages/next-international/src/app/client/create-use-current-locale.ts#L18, which should be a client only file. Somehow this is getting called on the server.

I only call useCurrentLocale in one place in my code, which is under 'use client', so I'm not sure how this is getting called and logged on the server.

<img width="857" alt="Captura de pantalla 2023-09-12 a la(s) 3 12 16 p m" src="https://github.com/QuiiBz/next-international/assets/954970/761b6bc0-4802-4c5c-a048-171f735181e9">

**About (please complete the following information):**
 - next-international 0.9.5
 - Next.js 13.4.0

**Comment by QuiiBz** [comment]
`'use client'` doesn't mean that the components are never rendered on the server: instead it means that these components can be rendered on the client, and they are also still pre-rendered on the server.

Could you try to update to `next-international@1.0.0-rc.6`? I've made some changes to this part of the library. You can check the upgrade guide here: https://github.com/QuiiBz/next-international/pull/126

**Comment by zackrw** [comment]
Love it! Will do and report back.

**Comment by zackrw** [comment]
@QuiiBz this went away with 1.0 ... closing it out, and thank you!
