### ISSUE TITLE
Nested locale object does not work in production

### ISSUE THREAD

**Issue by lindesvard** [QuiiBz/next-international#165]
Hey,

Noticed that nested object did not work for me when I built for production. Looked around in the source code and noticed the locale is not flattened for `getLocaleProps`. So when create-t tries to do ``let value = scope ? content[`${scope}.${key}`] : content[key];`` it would never find the values since content is a nested object.

Did these changes direct in node modules and it seems to resolve my issue. https://github.com/lindesvard/next-international/commit/d6394e558eafd69e23258dcbf243c4446aa0dd12

Using next pages as routing

**To Reproduce**

1. Just setup a new project with nested objects as translations. 
2. `npm run builld`
3. No values are shown

**Expected behavior**
Nested object should resolve in correct value and not display the key.

**About (please complete the following information):**
 - next-international version 0.9.5
 - Next.js version 13.4.19

**Comment by QuiiBz** [comment]
You're totally right. Would you like to send a PR since you already have a fork?

**Comment by lindesvard** [comment]
Here you have it. Not sure why vercel complaining tho https://github.com/QuiiBz/next-international/pull/166

**Comment by QuiiBz** [comment]
I'll wait a few days before triggering a new patch release, since 1.0.0 was released a few minutes ago.

**Comment by QuiiBz** [comment]
Fix released in https://github.com/QuiiBz/next-international/releases/tag/1.0.1!

**Comment by lindesvard** [comment]
Thanks! 🙏
