### ISSUE TITLE
Avoid wrapping every client components that needs translations

### ISSUE THREAD

**Issue by sshmaxime** [QuiiBz/next-international#170]
Hello, first of all thanks for your work on that library it has been really useful so far ! 

That being said, what is the rationale behind the fact that I need to wrap every client components that needs to call `useI18n` with `I18nProviderClient` ? Couldn't that be avoidable ? What could be the potential solutions to avoid doing that ?

**Comment by zackrw** [comment]
I think you only need to wrap layouts that will have client components rendered within their children prop? (And if you wrap a parent layout you never need to wrap a child layout.) So you only end up wrapping a few times in your whole codebase. 

Or maybe I am using it wrong.

Perhaps the wording can be slightly more clear?
<img width="820" alt="Captura de pantalla 2023-09-14 a la(s) 9 07 46 a m" src="https://github.com/QuiiBz/next-international/assets/954970/bc40d4b4-08b7-41d0-98f2-98ab18bf6e99">

**Comment by QuiiBz** [comment]
Agree that the docs can be improved. You can also create an intermediate component to avoid having the whole layout or page on the client:

```tsx
// in a new file
'use client'

function I18nProvider({ children }) {
  return <I18nProviderClient>{children}</I18nProviderClient>
}

// in your layout (note that it DOESN'T have 'use client'
export default function Layout({ children }) {
  return (
    <I18nProvider>
      {children}
    </I18nProvider>
  )
}
```

**Comment by sshmaxime** [comment]
Maybe the best/recommanded way should be to have a wrapper like `withI18n`, and then all you need to do is `withI18n(MyComponent)` in the clients components that needs `i18n` ?

**Comment by sshmaxime** [comment]
I did something like that:
```typescript
/**
 * Create i18n client.
 */
const I18nClient = createI18nClient(LocalesI18nConfig);

/**
 * Component wrapper for client components that needs i18n.
 */
export const withI18n = (Component: () => JSX.Element) => {
  return () => (
    <I18nClient.I18nProviderClient>
      <Component />
    </I18nClient.I18nProviderClient>
  );
};
```

And then:
```typescript
const MyComponent = () => {
  return <div>Hello</div>;
};

export default withI18n(MyComponent);
```

Cleaner imho.
And you just add that to any client components that needs `i18n`. @QuiiBz wdyt ?

**Comment by QuiiBz** [comment]
That works, but I personally prefer to have a single `I18nProviderClient` at the root of the app, since almost every sub-component will be localized. Using the snippet I shared above, it doesn't turn all pages and sub-components to client, meaning you'll still get great performance.

**Comment by sshmaxime** [comment]
Oh alright, now I understand. Well yeah much better your way @QuiiBz . Btw it might be nice to update the docs then because it was confusing, thank you 🙏
