### ISSUE TITLE
useChangeLocale() doesn't respect the "rewriteDefault" urlMappingStrategy option

### ISSUE THREAD

**Issue by olbrown** [QuiiBz/next-international#171]
**Describe the bug**
When calling the useChangeLocale() function to switch to the default locale, the default locale is still prefixed to the URL despite urlMappingStrategy being set to 'rewriteDefault'.

**To Reproduce**
1. Set urlMappingStrategy: rewriteDefault in middleware
2. Add in switch as in [example docs](https://github.com/QuiiBz/next-international/blob/main/examples/next-app/app/%5Blocale%5D/switch.tsx)
3. Switch to non-default locale
4. Switch back to default locale

**Expected behavior**
The URL should leave out the default locale prefix.

`http://localhost:3000/en/about` should be: 
`http://localhost:3000/about`

**About (please complete the following information):**
 - next-international version: 1.0.0
 - Next.js version: 13.4.19

**Comment by QuiiBz** [comment]
Fix released in https://github.com/QuiiBz/next-international/releases/tag/1.0.1!
