### ISSUE TITLE
[disccusion] is it ok to call setStaticParamsLocale in layout.tsx

### ISSUE THREAD

**Issue by landvibe** [QuiiBz/next-international#172]
Calling `setStaticParamsLocale` in every page.tsx is a cumbersome task.
It seems that calling `setStaticParamsLocale` in a dynamic page is also fine.
So, it's most convenient to call `setStaticParamsLocale` in the root's layout.tsx. Is that okay to do?

**Comment by QuiiBz** [comment]
Unfortunately, that's a Next.js issue. You can't share in-memory stuff from layouts to pages using `cache()`, that's we manually have to call `setStaticParamsLocale` on every page.

As soon as there is a way to share data from layouts down to pages, we'll update next-international to use it.
