### ISSUE TITLE
TypeScript Error When Using Object Notation for fallbackLocale

### ISSUE THREAD

**Issue by iroshahewage** [QuiiBz/next-international#173]
**Describe the bug**
I've encountered a bug in next-international when using Object notation for fallback Locale. It results in a TypeScript error.

**Screenshots**
![image](https://github.com/QuiiBz/next-international/assets/122591202/2829ab82-f4b1-4189-a148-189a8b509a9c)

**About**
 - next-international version 1.0.0
 - Next.js version 13.4.19

**Additional context**
This issue arises when defining locales using Object notation. When I use Dot notation, there's no problem.

**Comment by QuiiBz** [comment]
Good catch! Fixed in #174, I'll do a release very soon.

**Comment by QuiiBz** [comment]
Fix released in https://github.com/QuiiBz/next-international/releases/tag/1.0.1!
