### ISSUE TITLE
useCurrentLocale is working but not useI18n

### ISSUE THREAD

**Issue by zackrw** [QuiiBz/next-international#183]
**Describe the bug**
In a client component, I have useCurrentLocale() working (e.g. returns 'pt-BR') and getI18n() working on the SSR wrapper page. But useI18n is a no-op here.

Everything works on the homepage "/:locale", but on "/:locale/dashboard" it does not. changeLocale() is also not working on the dashboard. Has anyone else seen route-specific bugs?

![image](https://github.com/QuiiBz/next-international/assets/954970/8ba2ae84-cb1b-43ad-94ba-e602cb526375)

**About (please complete the following information):**
 - next-international version 1.0.1
 - Next.js version 13.4.0

**Comment by QuiiBz** [comment]
Can you share your middleware configuration, and share the code/a reproduction?

**Comment by QuiiBz** [comment]
Closing as no reproduction has been provided. Feel free to re-open if needed!

**Comment by zackrw** [comment]
I figured this out BTW. It was because a single client component was accidentally `async`, which caused everything to hang and/or behave unpredictably.
