### ISSUE TITLE
[Question] How to use the "fallbackLocale" in the i18nProviderClient "fallback" component?

### ISSUE THREAD

**Issue by gustaveWPM** [QuiiBz/next-international#189]
Hello there,

Given the following example:

```tsx
<I18nProviderClient fallback={<p> Loading...</p>} fallbackLocale={en}> 
```

I didn't understand how to do something like this (it obviously doesn't make sense to use `fallbackLocale` as a function here, but I guess this example would be sufficiently clear to help you to understand what I'm trying to do):

```tsx
<I18nProviderClient fallback={<p>{fallbackLocale('vocab.loading')}</p>} fallbackLocale={en}> 
```

In my project, I tried to use `getClientSideI18n()` in the code of my `fallback` component, but it doesn't seem to be the right way to do.

Is it even possible to achieve this at the moment?
Regards!

**Comment by gustaveWPM** [comment]
Uhhh, I'm so dumb.
Just made something like:

```ts
export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <I18nProviderClient fallbackLocale={fr}>
      <html lang={useCurrentLocale()}>
        <body className="flex flex-col min-h-screen">
          <SplashScreen />
          <NextTopLoader {...{ ...ProgressbarConfig.PROPS }} />
          <SitewideNavbar />
          {children}
        </body>
      </html>
    </I18nProviderClient>
  );
}
```

**Comment by QuiiBz** [comment]
This is the correct way to achieve what you want. Closing at it seems solved? But feel free to re-open if it's not the case!

**Comment by gustaveWPM** [comment]
Moving on: https://github.com/QuiiBz/next-international/issues/191
