### ISSUE TITLE
[I18nProviderClient] Display fallbackLocale values instead of raw locales keys?

### ISSUE THREAD

**Issue by gustaveWPM** [QuiiBz/next-international#191]
Hello.
I was expecting the `I18nProviderClient` to "Fallback" on the `fallbackLocale` values during the loading phase, instead of showing raw locales keys.
(In practical terms, it doesn't really matter since I've set up a _Splash Screen_ during this loading phase.)

![Raw locales keys](https://github.com/QuiiBz/next-international/assets/118654172/b2226cd9-2e99-4031-84c0-f77452efbb1e)

I just find this behavior rather curious.
Maybe I've misunderstood something and it's coming from my code?

```ts
// @/i18n/locales/fr
export default {
  _infos: {
    lng: 'fr',
    label: 'Français'
  },

  navbar: {
    home: 'Accueil',
    dashboard: 'Dashboard'
    // * ...
  }
} as const;
```

```ts
// lib/misc/getEnumsKeys.ts
export const getEnumKeys = (e: object): string[] => Object.keys(e).filter((key) => isNaN(Number(key)));
```

```ts
// config/i18n.ts
import defaultLanguage from '@/i18n/locales/fr';
export type VocabBase = typeof defaultLanguage;
export enum ELanguagesFlag {
  fr,
  en
}

export const DEFAULT_LANGUAGE = defaultLanguage._infos.lng;
export const LANGUAGES: LanguageFlag[] = getEnumKeys(ELanguagesFlag) as LanguageFlag[];

export { defaultLanguage as fallbackLocale };
```

```tsx
// src/app/[locale]/layout.tsx
<I18nProviderClient {...fallbackLocale}>
  <html lang={useCurrentLocale()}>
    <body className="flex flex-col h-screen w-full p-0 m-0">
      <SplashScreen />
      <NextTopLoader {...{ ...ProgressbarConfig.PROPS }} />
      <SitewideNavbar />
      {children}
    </body>
  </html>
</I18nProviderClient>;
```

```ts
// middleware.ts
const I18nMiddleware = createI18nMiddleware({
  locales: LANGUAGES,
  defaultLocale: DEFAULT_LANGUAGE,
  urlMappingStrategy: 'rewriteDefault'
});
```
https://github.com/Tirraa/dashboard_rtm/tree/6e8d75e0ad79d6dc9b8d1bd6bed4671193d9ada0

**Comment by gustaveWPM** [comment]
Probs related: https://github.com/QuiiBz/next-international/issues/190

**Comment by QuiiBz** [comment]
Thanks for the reproduction. I've just tried and the issue appears to be because of the spread of `fallbackLocale`. Inlining `fallbackLocale={fallbackLocale}` works as expected, and shows this locale immediately:

<img width="551" alt="Screenshot 2023-09-25 at 17 23 05" src="https://github.com/QuiiBz/next-international/assets/43268759/3757c034-07d9-42e5-b286-24f3a8bdd78b">

Feel free to re-open if needed!

**Comment by gustaveWPM** [comment]
It has fixed my problem, thank you.

**Comment by gustaveWPM** [comment]
I was misusing the spread operator

```tsx
    <I18nProviderClient {...{ fallbackLocale }}> // * ... Oops! Initially wrote: <I18nProviderClient {...fallbackLocale}>
```

This works exactly as:
```tsx
    <I18nProviderClient fallbackLocale={fallbackLocale}>
```

It was totally my fault.
