### ISSUE TITLE
How to use useI18n() in the client component?

### ISSUE THREAD

**Issue by trlanfeng** [QuiiBz/next-international#192]
How to use `useI18n` in a client-side component?
Just like in the example `examples/next-app/app/[locale]/switch.tsx`, but I want to add a "Switch Language" text that is obtained from a language file. However, when using `useI18n` in a client-side component, it prompts that it needs to be included in `I18nProviderClient`.

```
'use client';

import { useChangeLocale,useI18n } from '../../locales/client';

export function Switch() {
  const t = useI18n();
  const changeLocale = useChangeLocale();

  return (
    <>
      <label>{t('switch-language')}</label>
      <button type="button" onClick={() => changeLocale('en')}>
        EN
      </button>
      <button type="button" onClick={() => changeLocale('fr')}>
        FR
      </button>
    </>
  );
}
```

**Comment by gustaveWPM** [comment]
> it prompts that it needs to be included in `I18nProviderClient`.

Yes.

```ts
export default function RootLayout({ children }: LayoutMinimalProps) {
  return (
    <I18nProviderClient>
      <html lang={useCurrentLocale()}>
        <body className="flex flex-col h-screen w-full p-0 m-0">
          <SplashScreen />
          <NextTopLoader {...{ ...ProgressbarConfig.PROPS }} />
          <SessionProvider>
            <SitewideNavbar />
            {children}
          </SessionProvider>
        </body>
      </html>
    </I18nProviderClient>
  );
}
```

This doesn't seem to be a bug.

**Comment by QuiiBz** [comment]
You have to wrap your client components in `I18nProviderClient`. The easiest option is to do so in a layout: https://next-international.vercel.app/docs/app-setup#move-your-existing-files
