### ISSUE TITLE
Duplicate pages when using rewriteDefault

### ISSUE THREAD

**Issue by DennieMello** [QuiiBz/next-international#196]
**Is your feature request related to a problem? Please describe.**
Now, when using the option in urlMappingStrategy: 'rewriteDefault', we have two duplicate pages for the default language with and without /en. This is not very good for both SEO and users.

**Describe the solution you'd like**
It would be logical to redirect from all pages containing the default language in the url to pages without it.

**Comment by gustaveWPM** [comment]
You may also configure a 301 redirection, nope?

**Comment by DennieMello** [comment]
> I'm not sure we're really talking about duplicate pages/internal duplicate content.
> 
> The SSG only generates `/fr/*`, `/en/*`, `/it/*`, `/.../*` pages in my project, and it works well... (In fact, it works _almost_ well: there is an _another_ issue, way more concerning for SEO, that should be fixed soon, I hope. You can find more information about it here: #190).
> 
> If you're annoyed that the URL doesn't redirect the user immediately upon visiting the website, you can also set up a 301 redirect, nope?
> 
> I'm just afraid that redirecting from a `/en/*` page to a `/*` page will redirect to the last language stored on the user's side, though. Idk if that's the behaviour you want.
> 
> (I guess that `en` is your default language?)

Perhaps you have a different urlMappingStrategy value? With "rewriteDefault", pages with url /fr/*, /en/*..., are actually generated, but pages with defaultLocale are available both with and without locale specified. This leads to duplicate content.

301 redirect can be specified additionally in the middleware, but it seems to me that it would be more correct and safer to release this at the level of this module.

Are there any reasons why duplication of content may be necessary, both with and without the default locale prefix?

**Comment by QuiiBz** [comment]
Agree that when using `rewriteDefault`, the default locale shouldn't be reachable through a URL segment and should instead redirect to the correct URL. I've added this behavior in #204 and it will be released soon in #205
