### ISSUE TITLE
Storing searchParams after changing the language by useChangeLocale stopped working

### ISSUE THREAD

**Issue by slowwriter** [QuiiBz/next-international#200]
Storing searchParams after changing the language by useChangeLocale stopped working.
I implemented all the changes from the [release 1.0.0](https://github.com/QuiiBz/next-international/releases/1.0.0) description.

 - next-international version [e.g. 1.0.1]
 - Next.js version [e.g. 13.5.3]

**Comment by QuiiBz** [comment]
I had to remove this to support Static Rendering. We could add it again but that means users will have to wrap components using `useChangeLocale` in a `Suspense` boundary, which reduces the usefulness of Static Rendering: https://nextjs.org/docs/app/api-reference/functions/use-search-params#static-rendering

**Comment by slowwriter** [comment]
Is it possible to make this optional? Suspense wrapping only required for people who want to maintain searchParams?

**Comment by QuiiBz** [comment]
You'll have to wrap with `Suspense` if you want Static Rendering, but unfortunately, we can't call hooks conditionally.

What's your use case?

**Comment by QuiiBz** [comment]
I've published `next-international@1.1.0-rc.2` that introduces a new `preserveSearchParams` option in `useChangeLocale`.

You'll manually have to wrap the component using this hook in a `Suspense` boundary to prevent opting out the entire page from Static Rendering. See the documentation here: https://next-international-git-feat-110-quiibz.vercel.app/docs/app-get-change-locale#preserving-search-params

It will be released officially in #205
