### ISSUE TITLE
Variable appear for few second and then it switched back to string.

### ISSUE THREAD

**Issue by iStorry** [QuiiBz/next-international#210]
Whenever i refresh the page this happen

https://github.com/QuiiBz/next-international/assets/7252344/b9162d5e-c329-4891-af38-7067fc326c08

**Comment by iStorry** [comment]
After adding fallback locale it fixed the issue.
But fallback show loading for whole page is there anyway we can avoid that?

**Comment by QuiiBz** [comment]
It will be fixed by https://github.com/QuiiBz/next-international/pull/205, also related to https://github.com/QuiiBz/next-international/issues/209.
