### ISSUE TITLE
Zod support? 

### ISSUE THREAD

**Issue by iStorry** [QuiiBz/next-international#213]
Is there anyway i can use this zod library? 

```ts
export const signInSchema = z.object({
  email: z.string().email({ message: t("signIn.login") }),
  password: z.string().min(6, { message: t("signIn.password") }),
});
```

**Comment by QuiiBz** [comment]
I'm not too familiar with Zod, but I don't see why it wouldn't be possible. The only thing is that you have to create the schema when rendering a component, because you can only access the `t()` function there. Probably a good idea to wrap the schema in a memo too:

```ts
function Component() {
  const t = useI18n()

  const signInSchema = useMemo(() => z.object({
    email: z.string().email({ message: t('signIn.login') }),
    password: z.string().min(6, { message: t('signIn.password') })
  }), [t])

  return ...
}
```

**Comment by iStorry** [comment]
Hey thanks for reply. but signInSchema needs to be exported as well. This will not be issue if signInSchema is only getting used by that component 

This is how zod translation are supported in `i18next`

https://github.com/aiji42/zod-i18n

**Comment by QuiiBz** [comment]
Thanks for the link. When do you usually call `i18next.init` with the correct language? You'll likely have to do this inside a React component, right?

```ts
i18next.init({
  lng: "es",
  ...
})
```

If so, I believe it should be possible to do the same for next-international. Unfortunately, I don't have enough knowledge with Zod to add this feature, but I'd welcome any PR/help from the community!

**Comment by Yovach** [comment]
To be "compatible" with zod, I did something like the following
```typescript
import type { useI18n } from "~/locales/client";

export type TranslateFunc = Awaited<ReturnType<typeof useI18n>>;
export const validation = (t: TranslateFunc) =>
  z.object({
    username: z.string().min(3, z("...")),
    password: z.string().min(3, z("...")),
  });
```

I know it's not the best way to proceed, but it works well and so far I haven't encountered any problems.

**Comment by iStorry** [comment]
> Hi, To be "compatible" with zod, I did something like the following
> 
> ```ts
> import type { useI18n } from "~/locales/client";
> 
> export type TranslateFunc = Awaited<ReturnType<typeof useI18n>>;
> export const validation = (t: TranslateFunc) =>
>   z.object({
>     username: z.string().min(3, t("...")),
>     password: z.string().min(3, t("...")),
>   });
> ```
> 
> I know it's not the best way to proceed, but it works well and so far I haven't encountered any problems.

Thanks for the solution!
Have you tried getting typesof validation?

type Inputs = z.infer<typeof validation>; // This throw error. 

also react-hook-form throw an error 

const form = useForm<Inputs>({
    resolver: zodResolver(schema), // This throw error. 
})

**Comment by Yovach** [comment]
> > Hi, To be "compatible" with zod, I did something like the following
> > ```ts
> > import type { useI18n } from "~/locales/client";
> > 
> > export type TranslateFunc = Awaited<ReturnType<typeof useI18n>>;
> > export const validation = (t: TranslateFunc) =>
> >   z.object({
> >     username: z.string().min(3, t("...")),
> >     password: z.string().min(3, t("...")),
> >   });
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I know it's not the best way to proceed, but it works well and so far I haven't encountered any problems.
> 
> Thanks for the solution! Have you tried getting typesof validation?
> 
> ```ts
> type Inputs = z.infer<typeof validation>; // This throw an error. 
> ```
> 
> also react-hook-form throw an error
> 
> ```ts
> const form = useForm<Inputs>({
>     resolver: zodResolver(validation), // This throw an error. 
> })
> ```
> 
> @Yovach

Hi,

You can do this for the first :
```typescript
type Inputs = z.infer<ReturnType<typeof validation>>;
```

and this for react-hook-form, I think it'll works
```typescript
const t = useI18n();
const form = useForm<Inputs>({
    resolver: zodResolver(validation(t)), // This throw an error. 
})
```

**Comment by iStorry** [comment]
@Yovach Thanks

**Comment by QuiiBz** [comment]
Closing as it seems resolved, thanks for the help!
