### ISSUE TITLE
[next-international] Locale "serviceworker.js" not found in locales (en, fr), returning "notFound()"

### ISSUE THREAD

**Issue by medyahyejoud** [QuiiBz/next-international#219]
**Describe the bug**
next-international keeps logging out this error:
` ⨯ node_modules/.pnpm/next-international@1.0.1/node_modules/next-international/dist/app/server/index.js (175:61) @ eval
 ⨯ TypeError: locales[locale] is not a function
    at Generator.next (<anonymous>)
    at new Promise (<anonymous>)
    at NotFound (./app/[locale]/not-found.tsx:20:77)
    at stringify (<anonymous>)
null`

**To Reproduce**
here is a stripped down version fo the application to test, btw I'm using pnpm.
https://github.com/medyahyejoud/next_reprod.git

**Expected behavior**
App shouldn't log out this message, I've done everything correctly.

**Screenshots**
<img width="977" alt="Screenshot 2023-10-04 at 19 04 11" src="https://github.com/QuiiBz/next-international/assets/25517176/6397a5bc-33d5-4329-b564-c5e25fa1d23c">

**About (please complete the following information):**
 - next-international: "^1.0.1"
 - next: "13.5.4"

**Comment by gustaveWPM** [comment]
Ping @QuiiBz 

Hey, I think it is my fault.
https://github.com/QuiiBz/next-international/issues/144

**Comment by QuiiBz** [comment]
Thanks for the reproduction. I cloned and run the app, but I don't get any error on the server nor client:

<img width="604" alt="Screenshot 2023-10-05 at 10 34 41" src="https://github.com/QuiiBz/next-international/assets/43268759/57a7862a-41f1-49a1-9e28-ccd5d5b10e90">

Do you have any extension in your browser that could fetch this `service worker.js` file? You can try by going into private browsing.

As @gustaveWPM mentioned, you can also add `serviceworker.js` inside the `matcher` configuration of your middleware: https://github.com/medyahyejoud/next_reprod/blob/493d26bb1ffa4140f407f6a38ceda5004850308f/middleware.ts#L16

```ts
export const config = {
  matcher: ["/((?!api|static|.*\\..*|_next|favicon.ico|robots.txt|serviceworker.js).*)"],
};
```

**Comment by medyahyejoud** [comment]
Hey guys,

Hey @QuiiBz, thanks a bunch! I totally overlooked the isolated mode for opening the app. Just like you said, the issue got sorted out—it turned out to be the localhost cache and site data, possibly from other apps running on the same port. 🙌
