### ISSUE TITLE
[Code Safety][Suggestion] Type more strictly ImportedLocales

### ISSUE THREAD

**Issue by gustaveWPM** [QuiiBz/next-international#221]
At the moment, `ImportedLocales` is typed as follows:

```ts
type ImportedLocales = Record<string, () => Promise<any>>;
```

I find this troublesome because the leaf nodes of the vocabulary objects should be ALWAYS _strings_ (unless I've missed something?).

We could perhaps create a `LocaleData` type that forces the object's leaf nodes to be only _strings_.

```ts
type LocaleValue = string; // * ... sum type

type LocaleData = {
  [_: string]: LocaleData | LocaleValue;
};
```

---

> EDIT: actually, `LocaleValue` already exists in _international-types_.
> But I don't understand why it could be also a `number`, or a `boolean`, or `null` or `undefined`? :/
> Is it to be 100% compatible with JSON standards? If so, `undefined` is inappropriate. And I _think_ that `undefined` is inappropriate in any case.
> However, I admit that I didn't think about `Date`, which is highly desirable.
```ts
export type LocaleValue = string | number | boolean | null | undefined | Date; // * ... LocaleValue, as defined in international-types
```

---

So, we could do:

```ts
type ImportedLocales = Record<string, () => Promise<LocaleData>>;
```

Maybe like this? (I _think_ this code snippet illustrates my idea quite well.)

```ts
type LocaleData = {
  [_: string]: LocaleData | LocaleValue;
};

const localesToImport = {
  en: () => import('@/i18n/locales/en')
};

function doImports(importedLocales: Record<string, () => Promise<LocaleData>>) {
  // * ...
}

doImports(localesToImport);
```

---

I find it really unfortunate that currently, it is possible to write things like this without encountering any typing errors at build:

```ts
// locales/en.ts

export default {
  whatever: {
    valid: 'en', // * ... Is a string
    invalid: 12 // * ... Is a number
  }
} as const;
```

```ts
// client.ts

import { createI18nClient } from 'next-international/client';

export const { useI18n: getClientSideI18n, useScopedI18n, I18nProviderClient, useCurrentLocale } = createI18nClient({
  en: () => import('@/i18n/locales/en'),
});
```

```ts
// server.ts

import { createI18nServer } from 'next-international/server';

export const { getI18n: getServerSideI18n, getScopedI18n, getStaticParams } = createI18nServer({
  en: () => import('@/i18n/locales/en'),
});
```

**Comment by gustaveWPM** [comment]
Just to give an idea:

```ts
type JSONPrimitiveLeafs = string | number | boolean | null;
type JSONLeafs = JSONPrimitiveLeafs | JSONPrimitiveLeafs[];

export type JSONData = {
  [_: string]: JSONData | JSONData[] | JSONLeafs;
};

export type TypedLeafsJSONData<LeafsTypes extends JSONLeafs, AllowObjArrays extends 'ALLOW_OBJ_ARRAYS' | never = never> = {
  [_: string]: TypedLeafsJSONData<LeafsTypes> | (AllowObjArrays extends never ? never : TypedLeafsJSONData<LeafsTypes>[]) | LeafsTypes;
};
```

```ts
export enum ELanguagesFlag {
  fr,
  en
}
```

```ts
type LanguageFlagKey = keyof typeof ELanguagesFlag;
export type LanguageFlag = LanguageFlagKey;
export type LocalesGetterConfigObjTypeConstraint = Record<LanguageFlag, () => Promise<TypedLeafsJSONData<string>>>;
```

```ts
import { LocalesGetterConfigObjTypeConstraint } from '@/types/i18n';

const getLocales = () =>
  ({
    fr: () => import('@/i18n/locales/fr'),
    en: () => import('@/i18n/locales/en')
  } satisfies LocalesGetterConfigObjTypeConstraint);

export const locales = getLocales();
export default locales;
```

```ts
import { createI18nClient } from 'next-international/client';
import { locales } from './getLocales';

export const { useI18n: getClientSideI18n, useScopedI18n, I18nProviderClient, useCurrentLocale } = createI18nClient(locales);
```

```ts
import { createI18nServer } from 'next-international/server';
import { locales } from './getLocales';

export const { getI18n: getServerSideI18n, getScopedI18n, getStaticParams } = createI18nServer(locales);
```

**Comment by QuiiBz** [comment]
I just tried restricting `ImportedLocales` to be `Record<string, () => Promise<{ default: Record<string, unknown> }>>`, and while it can help a bit, it still allows the import any module that has a default export being an object. I can even import a `next.config.js` file and it will work, which makes sense because it matches the signature. It would only restrict importing non-js/ts files, or files not exporting a default object (which again, can be biased).

Because of this, I don't think going further in this direction will really improve the DX. It's already pretty clear from the documentation and examples that the locales file must match this specific signature.

Quick note: `LocaleValue` isn't meant to be used as the value of locales object, these should only be strings. Instead, it should only be used as the possible values of parameters when translating.

**Comment by gustaveWPM** [comment]
> I just tried restricting `ImportedLocales` to be `Record<string, () => Promise<{ default: Record<string, unknown> }>>`, and while it can help a bit, it still allows the import any module that has a default export being an object. I can even import a `next.config.js` file and it will work, which makes sense because it matches the signature. It would only restrict importing non-js/ts files, or files not exporting a default object (which again, can be biased).
> 
> Because of this, I don't think going further in this direction will really improve the DX. It's already pretty clear from the documentation and examples that the locales file must match this specific signature.
> 
> Quick note: `LocaleValue` isn't meant to be used as the value of locales object, these should only be strings. Instead, it should only be used as the possible values of parameters when translating.

Oh, okay.
I'm sorry, I didn't quite understand everything, and in the end my solution was really poor.

I was wrong!

**Comment by QuiiBz** [comment]
Nothing wrong with being wrong! It's still interesting to understand the specifics and the why/how. Thanks for the suggestion!
