### ISSUE TITLE
[v1.1.0][Bug?](Reproducible from repo examples) Warning: Cannot update a component (`HotReload`) while rendering a different component (`I18nProviderClient`).

### ISSUE THREAD

**Issue by gustaveWPM** [QuiiBz/next-international#228]
Hello,
I tried _Next International_ v1.1.0.

I face a problem when I use the next/prev buttons of my browser.
It's maybe a _high-priority_ issue, so here's how to reproduce it quickly.

---

To reproduce (using the [`next-app` example](https://github.com/QuiiBz/next-international/blob/main/examples/next-app/)):
- You can edit the [`examples/next-app/package.json`](https://github.com/QuiiBz/next-international/blob/main/examples/next-app/package.json) file to force _Next International_ v1.1.0: `"next-international": "1.1.0",`
  - Then `yarn install`
- Use `yarn run dev` (the issue is the same with a `build` then `start`, but you won't have the stacktrace in your browser console...).
- Browse the website
- Use next/prev buttons till it breaks

(Those screens come from my project but I think it doesn't matter in terms of reasoning.)

![image](https://github.com/QuiiBz/next-international/assets/118654172/97f56372-5ccf-4a53-b845-75abb373c8aa)

![image](https://github.com/QuiiBz/next-international/assets/118654172/500efdfa-a41c-4a4b-ac75-a29d61e765bd)

**Comment by QuiiBz** [comment]
This issue was fixed in 1.1.1
