### ISSUE TITLE
Without react full server side 

### ISSUE THREAD

**Issue by yovanoc** [QuiiBz/next-international#229]
I was wondering if we could use the server sides methods without react and nextjs at all? thanks

**Comment by QuiiBz** [comment]
That's currently not exposed and only used internally to use the same code between the Pages & App Router. 

Could you share your use-case? next-international focuses solely on Next.js.

**Comment by yovanoc** [comment]
I see. The use case is a monorepo with different nextjs apps and other apps like api and services. 
I would like to share the same 'translate' package that would be created inside the monorepo and share the translate methods to the nextjs apps, but with the services too, thanks for your time

**Comment by QuiiBz** [comment]
That seems like a valid use-case. The [`createT` function](https://github.com/QuiiBz/next-international/blob/main/packages/next-international/src/common/create-t.ts) will be exposed in the next release.

**Comment by yovanoc** [comment]
Thanks I will see how it works then !

**Comment by QuiiBz** [comment]
Released in [next-international@1.1.2](https://github.com/QuiiBz/next-international/releases/tag/1.1.2)!
