### ISSUE TITLE
Needless extra parameter required to avoid TS errors

### ISSUE THREAD

**Issue by rentalhost** [QuiiBz/next-international#231]
**Describe the bug**
When using the `createI18nServer` (or _client_) function to create internationalization providers with _locales_ provided from an external source, the `t` function (e.g., `t("example")`) generates a TypeScript error, indicating that _two arguments are expected, but only one is provided_.

**To Reproduce**
1. Define locales using an external source, as described in the code snippet below.
2. Use the `t` function with a single parameter, e.g., `t("example")`.

```ts
import { createI18nServer } from "next-international/server";

// External source for locales, for example purposes, provided as an array.
const locales = ["en", "pt"];

export const { getI18n } = createI18nServer(
  Object.fromEntries(
    locales.map((locale) => [locale, () => import(`./${locale}`)]),
  ),
);

```

**Expected behavior**
I expected the `t` function to work with a single parameter (`t("example")`) without generating TypeScript errors.

**Screenshots**
![image](https://github.com/QuiiBz/next-international/assets/421851/759d187f-c828-494e-9761-92b77e28ee1a)
![image](https://github.com/QuiiBz/next-international/assets/421851/d5b37451-b77f-4186-88d0-e26971f252ce)

**About (please complete the following information):**

next-international version: 1.1.1
Next.js version: 13.5.4
TypeScript version: 5.2.2

**Additional context**

I created a [**CodeSandbox**](https://codesandbox.io/p/sandbox/next-international-issue-1-sjwpm9?file=%2Fapp%2F%5Blocale%5D%2Fpage.tsx%3A8%2C1) to illustrate the issue. Despite the TypeScript error, the translated text ("_example in en_") appears as expected. It seems that the usage of `Object.fromEntries()` in conjunction with external locales may be causing this issue.

**Comment by QuiiBz** [comment]
As expected, the issue comes from this `Object.fromEntries` that doesn't narrow the correct type information:

<img width="526" alt="Screenshot 2023-10-08 at 09 09 39" src="https://github.com/QuiiBz/next-international/assets/43268759/931a2e31-3a92-4718-a67c-50126d21542f">

You can manually cast the result to get the correct type:

```ts
import { createI18nServer } from "next-international/server";

const locales = ["en", "pt"] as const;

export const { getI18n } = createI18nServer(
  Object.fromEntries(
    locales.map((locale) => [locale, () => import(`./${locale}`)]),
  ) as Record<(typeof locales)[number], () => Promise<typeof import('./en')>>
);
```

**Comment by rentalhost** [comment]
Perfect, I'll give it a try. I almost tried to do this but thought it wouldn't work and gave up (I was having trouble understanding the return precisely, which, in the end, was exactly the same problem that TS was having because of my mistake haha). Anyway, I thought TS would be able to understand the return on its own, but it seems to be having some kind of issue with `Object.fromEntries()` that starts returning an `any` instead of the precise type (even when using `as consts`).

**Comment by gustaveWPM** [comment]
> ```ts
> const locales = ["en", "pt"] as const;
> ```

Hi, I tried it, but when I call `globalT`, it seems that it doesn't solve the problem. :(
```ts
  const globalT = await getServerSideI18n();
  globalT('')
```

**Comment by QuiiBz** [comment]
Yeah unfortunately many of these internal JS methods often return types that aren't narrowed properly and are too wide, for reasons that I ignore. I've tried on your CodeSanbox and it was working fine!
