### ISSUE TITLE
getLocaleProps gives any types for getServerSideProps context

### ISSUE THREAD

**Issue by ImamAlfariziSyahputra** [QuiiBz/next-international#233]
**Describe the bug**
`getLocaleProps` does not give the proper types. Am i doing something wrong here?

<img width="773" alt="image" src="https://github.com/QuiiBz/next-international/assets/63343105/fc064f31-3183-41ec-b6b9-6ede8f798301">

-----------

**About (please complete the following information):**
 - next-international version 1.1.1
 - Next.js version 13.4.4

**Comment by QuiiBz** [comment]
You have to manually type `ctx`, because we don't know if it's being used with `getServerSideProps` or `getStaticProps`:

```ts
export const getServerSideProps = getLocaleProps(async (ctx: GetServerSidePropsContext) => {
  return {
    props: {},
  };
});
```

**Comment by ImamAlfariziSyahputra** [comment]
> You have to manually type `ctx`, because we don't know if it's being used with `getServerSideProps` or `getStaticProps`:
> 
> ```ts
> export const getServerSideProps = getLocaleProps(async (ctx: GetServerSidePropsContext) => {
>   return {
>     props: {},
>   };
> });
> ```

okay that code is working fine, but @QuiiBz can you give me an example to fix this type error, it's happen when i'm using `satisfies GetServerSideProps<Props>`. i just want to follow the nextjs docs example.

<img width="844" alt="image" src="https://github.com/QuiiBz/next-international/assets/63343105/47f0c446-ec5d-4520-a999-22d5d0b713ed">

**Comment by ImamAlfariziSyahputra** [comment]
> Works fine on my side, the `id` you're returning is a `number` instead of a `string` as specified in `HomeProps`:
> 
> ```ts
> export const getServerSideProps = getLocaleProps(async (ctx: GetServerSidePropsContext) => {
>   return {
>     props: {
>       id: '1',
>     },
>   };
> }) satisfies GetServerSideProps<HomeProps>;
> ```

oh sorry i didn't see that, thank you for your response😁
