### ISSUE TITLE
is I18nProvider block the SEO?

### ISSUE THREAD

**Issue by ImamAlfariziSyahputra** [QuiiBz/next-international#235]
**Describe the bug**
i'm using pages directory. after i'm wrapping my app with `I18nProvider`, the SEO is gone, when i see the `page source`, i just got an empty `div`, but if i remove the `I18nProvider` i got the full html. Can you give me explanation about this? thanks.

**Screenshots**
1. with `I18nProvider`
    <img width="1273" alt="image" src="https://github.com/QuiiBz/next-international/assets/63343105/99931f6c-e382-44f2-b40d-d45c82df7595">
2. without
    <img width="1266" alt="image" src="https://github.com/QuiiBz/next-international/assets/63343105/e1be6695-ea17-4933-af30-e67a724ad2ed">

**About (please complete the following information):**
 - next-international version 1.1.1
 - Next.js version 13.4.4

**Comment by QuiiBz** [comment]
See the Static Site Generation documentation here: https://next-international.vercel.app/docs/pages-static-site-generation

You have to use `getStaticProps` or `getServerSideProps` to SSR the initial page. See also the example here: https://github.com/QuiiBz/next-international/blob/62fe48b48f423d6183e4d41ea863a37fe7fe48d2/examples/next-pages/pages/ssr-ssg.tsx#L4
