### ISSUE TITLE
TypeError: locales[locale] is not a function

### ISSUE THREAD

**Issue by stefanlogue** [QuiiBz/next-international#239]
**Describe the bug**
When viewing a page using a locale that is not the default locale, I get this error:

```bash
node_modules/next-international/dist/app/server/index.js (180:61) @ eval
 ⨯ TypeError: locales[locale] is not a function
    at Generator.next (<anonymous>)
    at new Promise (<anonymous>)
    at OverviewLayout (house/[id]/overview/layout.tsx:23:85)
    at async Promise.all (index 0)
    at async Promise.all (index 0)
    at async Promise.all (index 0)
```

This also happens when I try to use the `getI18n` function in the `generateMetadata` function in order to translate the page title

**To Reproduce**

**Expected behavior**
Shouldn't get an error, should just translate the page correctly as it does with the default locale.

**Screenshots**
<img width="995" alt="Screenshot 2023-10-11 at 15 50 31" src="https://github.com/QuiiBz/next-international/assets/28792194/f38da986-a734-4457-8782-116ab36c8fb0">
<img width="1004" alt="Screenshot 2023-10-11 at 15 51 32" src="https://github.com/QuiiBz/next-international/assets/28792194/96a3fc72-de2b-4010-a21f-b3de445c4324">

**About (please complete the following information):**
 - next-international version [1.1.2-rc.1]
 - Next.js version [e.g. 13.5.4]

**Additional context**

**Comment by QuiiBz** [comment]
> To Reproduce
> Steps to reproduce the behavior:
> 
> Go to '...'
> Click on '....'
> Scroll down to '....'
> See error

I cannot help without a reproduction, as this error doesn't happen in the [example](https://github.com/QuiiBz/next-international/tree/main/examples/next-app) or the [CodeSandbox](https://codesandbox.io/p/sandbox/jovial-paper-skkprk?file=%2Fapp%2F%5Blocale%5D%2Fpage.tsx%3A1%2C1). Please provide a repository or Stackblitz/CodeSandbox so we can look into that.

It might also be related to https://github.com/QuiiBz/next-international/issues/219 or https://github.com/QuiiBz/next-international/issues/193 (specifically https://github.com/QuiiBz/next-international/issues/193#issuecomment-1733918687)

**Comment by iStorry** [comment]
I am getting the same issue 
![image](https://github.com/QuiiBz/next-international/assets/7252344/36671ef5-b332-490b-baf0-434435e8acd4)

**Comment by iStorry** [comment]
Update, I fixed it. 

For my case i was using fallbackLocale so i had to remove that and add locale to it.

![image](https://github.com/QuiiBz/next-international/assets/7252344/9127e900-096c-48ac-9114-471a4ad445b3)

That fixed everything. 

Please look into this 
https://next-international.vercel.app/docs/app-setup#move-your-existing-files @stefanlogue

**Comment by QuiiBz** [comment]
See the migration guide in the release note for 1.1.0: https://github.com/QuiiBz/next-international/releases/tag/1.1.0 (Support Static Rendering in nested Client Components)
