### ISSUE TITLE
On cookies

### ISSUE THREAD

**Issue by kristofferso** [QuiiBz/next-international#240]
I'm using Firefox, which is showing some warnings about the Next-Locale cookie misusing the [samesite attribute](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie#samesitesamesite-value). Since the cookie is not used by third parties, it's not really an issue. However it got me thinking about if this package could be used cookielss. The locale is always stored in the url anyways for all page requests. Is it necessary? Could `next-international` be expanded to support this?

**Comment by gustaveWPM** [comment]
This problem has already been discussed here: https://github.com/QuiiBz/next-international/issues/188
And I think this is indeed the path _Next International_ intends to take?

**Comment by QuiiBz** [comment]
The cookie is currently used to retrieve the previous locale if a user comes back to your site. I'm not too familiar with the `SameSite` or other cookie attributes, but if it produces a warning, we should fix it.

**Comment by QuiiBz** [comment]
Closing as we don't have more information for now, but happy to go forward and fix any issue/warning in our current cookies usage.

**Comment by kristofferso** [comment]
Added a PR here: https://github.com/QuiiBz/next-international/pull/269
