### ISSUE TITLE
preserveSearchParams:true not working with urlMappingStrategy: 'rewrite'

### ISSUE THREAD

**Issue by thainv92** [QuiiBz/next-international#245]
I use next-international 1.1.2 and next 13.5.2 
I use function Preserving search params, but i not working when I use urlMappingStrategy: 'rewrite'
const changeLocale = useChangeLocale({ preserveSearchParams: true })

This is my codesanbox: [https://codesandbox.io/p/sandbox/next-international-app-router-forked-qh8w43?file=%2Fmiddleware.ts%3A7%2C33](url)

**Comment by QuiiBz** [comment]
Fix (#246) released in https://github.com/QuiiBz/next-international/releases/tag/1.1.3!

**Comment by thainv92** [comment]
Great ! 
It working well on version 1.1.3. 
Thanks, bro !
