### ISSUE TITLE
Issue while switching language 

### ISSUE THREAD

**Issue by iStorry** [QuiiBz/next-international#250]
When ever i change the language it crashes the application. I can't tell weather it's `MDX` issue or `next-international`

<img width="792" alt="image" src="https://github.com/QuiiBz/next-international/assets/7252344/0d7d8734-a779-4446-bd66-b0c22f9fc2b4">

I've created the repo with basic fresh project. Please check 

[https://github.com/iStorry/mdx-next-international-test](https://github.com/iStorry/mdx-next-international-test)

**Comment by petyosi** [comment]
mdxeditor author here, I traced down the problem in the editor to this piece in my code (lives in useEffect):

```tsx
    document.body.appendChild(popupContainer)
    editorRootElementRef.current = popupContainer
    setEditorRootElementRef(editorRootElementRef)
    return () => {
      document.body.removeChild(popupContainer)
    }
```

Apparently, by the time the editor is unmounted, the popup container is no longer a direct child of the body element. I find this weird. 

This is the fix: https://github.com/mdx-editor/editor/commit/5de52ad2c12eebdfe39f3ddb0f3ae13b857d7243. However, this might cause issues with other libraries who manage popups by moving them to the body.

**Comment by iStorry** [comment]
@petyosi Thank you for the quick response.
