### ISSUE TITLE
The url doesn't change when has dot.

### ISSUE THREAD

**Issue by kindslayer** [QuiiBz/next-international#253]
**Describe the bug**
When url contains (.) the url doesn't change to locales.

i have this url: 
example.com/exam.ple

Normally, we should be redirected to the following address, but it is not done
example.com/en/exam.ple

 - next-international version [e.g. 1.1.3]
 - Next.js version [e.g. 13.5.6]

**Comment by QuiiBz** [comment]
Just curious, why do you have URLs with dots?

**Comment by kindslayer** [comment]
I have urls like this man:
example.com/logo.svg
example.com/robots.txt
example.com/sitemap.xml
example.com/slide1.png

These addresses will exist in every project.
I think if we have a whitelist extentions or whitelist for mimetype this problem is gone.
Tell me your opinion so that we can consider the changes and send a pull request

**Comment by QuiiBz** [comment]
These files should be in the `public` directory if possible - and if they need to be inside the `app` directory, you can exclude them from the middleware using the matcher config, as shown in the docs:

```ts
export const config = {
                                          // add any other file here
  matcher: ['/((?!api|static|.*\\..*|_next|favicon.ico|robots.txt).*)']
}
```
