### ISSUE TITLE
nextjs 13 SPA with some components use client, 

### ISSUE THREAD

**Issue by MiguelSilvaViana** [QuiiBz/next-international#259]
I'm creating a spa with nextjs 13, I only have a few components that need to be useClient, but they are useClient and I need to initialize the I18nProviderClient in the layout to use the translation, in this case I didn't want to put it in my single page layout, being a spa because I think it would disrupt the seo, so much so that I can't use title or description in my layout after passing it to use client, in this case for these use client components to be able to use the translation I should create a custom layout for these components and place them in a separate folder within components? I don't know if I managed to explain it correctly but if anyone has an example of this how I can do it I would really appreciate it, or tell me if I put use client in the layout if it wouldn't mess up the seo that would be the easiest solution.

I have a single layout, do I need to initialize the provider in the global layout? or I can create a custom layout for components that need to be client-side and need translation.

**Comment by QuiiBz** [comment]
If I understood correctly, you're asking how to use `I18nProviderClient` without switching a whole layout to be `'use client'`?

If so, you can move the `I18nProviderClient` logic to a separate component that is `'use client'`, and then use this component inside any layout, without the need for it to be `'use client'`

You can also check out the example, specifically this line: https://github.com/QuiiBz/next-international/blob/e0bad163fece71bce4d333fad533d5c75a1275c7/examples/next-app/app/%5Blocale%5D/client/layout.tsx#L5 with the `Provider` component being https://github.com/QuiiBz/next-international/blob/main/examples/next-app/app/%5Blocale%5D/provider.tsx

See also https://github.com/QuiiBz/next-international/issues/170#issuecomment-1719794154 for an example of the above.

**Comment by MiguelSilvaViana** [comment]
Exactly the same as question #170, thank you very much, encapsulating my root layout with the Provider component that you gave as an example worked perfectly.
