### ISSUE TITLE
Build issues (Export encountered errors on following paths: /_not-found)

### ISSUE THREAD

**Issue by Pavelas** [QuiiBz/next-international#262]
**Describe the bug**
It's impossible to build the app because for some reasons it throws an error.

```
 ✓ Creating an optimized production build
 ✓ Compiled successfully
 ✓ Linting and checking validity of types
 ✓ Collecting page data
   Generating static pages (0/4)  [    ]Error: Could not find locale while pre-rendering page, make sure you called `setStaticParamsLocale` at the top of your pages

Error occurred prerendering page "/_not-found". Read more: https://nextjs.org/docs/messages/prerender-error
Error: Could not find locale while pre-rendering page, make sure you called `setStaticParamsLocale` at the top of your pages

> Export encountered errors on following paths:
	/_not-found
```

- I don't have any `_not-found` files in my project.
- I have no static pages in my project as well, the problem comes from `/_not-found` file.
- I was trying to create `not-found.tsx` file in `[locale]` directory, it does not help.

**To Reproduce**
`pnpm build`

**Expected behavior**
It should build without any errors.

**About (please complete the following information):**
 - next-international version: **1.1.3**
 - Next.js version: **13.5.6**

**Comment by QuiiBz** [comment]
Can you share a minimal reproduction? Looking at the error, it seems like you're never calling `setStaticParamsLocale`: https://next-international.vercel.app/docs/app-static-rendering#static-rendering

**Comment by QuiiBz** [comment]
Closing for now, happy to re-open and help when we have more information.
