### ISSUE TITLE
Plurals |  some options not working or docs are outdated

### ISSUE THREAD

**Issue by bastibuck** [QuiiBz/next-international#266]
**Describe the bug**
The [docs](https://next-international.vercel.app/docs/app-plurals) state that you could use e.g. `#few` or `#many` with your translation keys. This seems to be not the case.

**To Reproduce**
Check CodeSandbox https://codesandbox.io/p/sandbox/jovial-paper-skkprk?file=%2Flocales%2Fen.ts%3A9%2C1-11%2C1

**Expected behavior**
Either the translations should be picked up correctly or the docs shuld be updated and remove the non-working hashes.

**Comment by bastibuck** [comment]
If it is only the docs I can file a PR for that but wanted to make sure what if this is intended to work or not

**Comment by QuiiBz** [comment]
This is not really a bug, but rather how the `Intl.PluralRules` API works (and we use it internally). Different keywords have different meanings based on the language, and its the case for `few` & `many`.

See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/PluralRules#using_locales:
<img width="882" alt="Screenshot 2023-10-23 at 17 12 31" src="https://github.com/QuiiBz/next-international/assets/43268759/1e41ef9a-aca2-4334-952c-3276a4113425">
