### ISSUE TITLE
How to work with custom `not-found.tsx` and `error.tsx` with app router static export?

### ISSUE THREAD

**Issue by alienzhangyw** [QuiiBz/next-international#268]
They're not working after I put all files into [locale] folder.
My file struct:
![image](https://github.com/QuiiBz/next-international/assets/58874541/f740350b-dbe6-4281-ba54-f84db0af1251)

localhost:4000/404 showing error:
![image](https://github.com/QuiiBz/next-international/assets/58874541/a2818f99-b751-4d1d-b0ed-4eff71f17dd8)

localhost:4000/en-US/404 showing white screen and multiple console errors:
![image](https://github.com/QuiiBz/next-international/assets/58874541/071cd210-a9c9-4259-a067-cd9af6c5eb38)

Related issue: https://github.com/vercel/next.js/issues/54239

**Comment by QuiiBz** [comment]
This seems like an issue with Next.js, and not specifically related to next-international. Apparently you have to move `not-found.tsx` outside the `[locale]` folder, directly into `app`, with an empty layout file.

**Comment by alienzhangyw** [comment]
> This seems like an issue with Next.js, and not specifically related to next-international. Apparently you have to move `not-found.tsx` outside the `[locale]` folder, directly into `app`, with an empty layout file.

But I cannot internatianlize the custom 404 page if I move it out

**Comment by QuiiBz** [comment]
> But I cannot internationalize the custom 404 page if I move it out


Yes I known, but I don't have any other solution for now since this is a Next.js bug :(

**Comment by alienzhangyw** [comment]
OK, close for now.

**Comment by kiennt2** [comment]
https://github.com/vercel/next.js/issues/55555#issuecomment-1724887409

try this, it work for me :D
