### ISSUE TITLE
Translation problem with mapped array

### ISSUE THREAD

**Issue by kutaysendil** [QuiiBz/next-international#275]
i have an array like that ; 
`
navItems: [
		{
			label: 'blog',
			href: '/blog',
		},
		{
			label: 'reservation',
			href: '/reservation',
		},
		{
			label: 'help',
			href: '/help',
		},
	]
`

and i mapped that array like that ;
`
{navItems.map(item => (
						<NavbarItem
							key={item.href}
							className='rightToLeft hidden xl:flex'
							isActive={pathname.startsWith(item.href)}>
							<NextLink href={item.href}>{t(item.label)}</NextLink>
						</NavbarItem>
					))}
`
its worked properly on dev mode but  ts throw error like that :
`Expected 2 arguments, but got 1.ts(2554)
index.d.ts(10, 2259): Arguments for the rest parameter 'params' were not provided.
(parameter) item: {
    label: string;
    href: string;
}`					
and i can not get build because of that error.	

** i tried ts-ignore error gone but still i can not build. 
 
 that is build error  :
 
    Linting and checking validity of types  ...Failed to compile.

./src/app/[locale]/page.tsx:14:9
Type error: Expected 2 arguments, but got 1.

  12 |                  {session && <div className=' '>{session.user.accessToken}</div>}
  13 |                  <div>
> 14 |                          <p>{t('help')}</p>
     |                              ^

thanks

**Comment by QuiiBz** [comment]
Hi, could you share a reproduction? It's a bit difficult to understand your issue.

**Comment by QuiiBz** [comment]
You might want to add `as const` to your `navItems` array to get the proper type for `label` inside the map: https://tsplay.dev/WKrXpm

<img width="1125" alt="Screenshot 2023-11-01 at 15 12 59" src="https://github.com/QuiiBz/next-international/assets/43268759/de6aefad-79f2-417e-95de-53e600d8039f">

**Comment by kutaysendil** [comment]
Thanks mate its workin ! <3
