### ISSUE TITLE
locales[locale] is not a function

### ISSUE THREAD

**Issue by leonardoRocchini** [QuiiBz/next-international#276]
**Describe the bug**
When I attempt to use "next-international" with a Next.js 14 app in the server component, the app returns the following error: "Error: locales[locale] is not a function.

**To Reproduce**
Use the basic example from CodeSandbox [example](https://codesandbox.io/p/sandbox/jovial-paper-skkprk?file=%2Fapp%2F%5Blocale%5D%2Fpage.tsx%3A1%2C1)

**Screenshots**
![Screenshot 2023-11-02 171406](https://github.com/QuiiBz/next-international/assets/62795461/3c4e6e3a-853c-48f5-8095-be96a1262c37)

**About (please complete the following information):**
 - next-international version 1.1.3
 - Next.js version 14.0.1.

**Comment by QuiiBz** [comment]
I'm not able to reproduce the issue using the link you provided, could you share a video?

**Comment by 7system7** [comment]
I have the same problem.

**Comment by leonardoRocchini** [comment]
Thank you, it seems that #193 has solved the problem.
