### ISSUE TITLE
Can't resolve 'next-international/middleware'

### ISSUE THREAD

**Issue by Crayon-ShinChan** [QuiiBz/next-international#277]
**Describe the bug**
Clone repo, go to example, next-app, pnpm i, then pnpm dev met `Can't resolve 'next-international/middleware'`

**To Reproduce**
1. Go to`example/next-app/`
2. pnpm i
3. pnpm dev

**Expected behavior**
No error

**Screenshots**
![CleanShot 2023-11-02 at 16 10 57@2x](https://github.com/QuiiBz/next-international/assets/38809606/58ac26b8-c406-4212-957d-6b3a973baa3c)

**About (please complete the following information):**
main branch on 2023-11-02

**Comment by QuiiBz** [comment]
You have to build both `packages/next-international` & `packages/international-types` first - I'll open another issue to add a proper `CONTRIBUTING.md` documentation.
