### ISSUE TITLE
Plural translations (with count paramater) does not match server-rendered HTML

### ISSUE THREAD

**Issue by nikitastryuk** [QuiiBz/next-international#281]
**Describe the bug**
Plural translations (with count paramater) which uses "Intl.PluralRules" API determined incorrectly on server ("ua" locale).

**locale.ts file**
`
{
  'test#one': '{count} #one',
  'test#other': '{count} #other',
}`

**Issue**
`<p>{t('test', { count: 21 })}</p>`

`#other` is returned from server-rendered html and then transformed to` #one` on client side.

**To Reproduce**
1. Go to [Sandbox](https://codesandbox.io/p/sandbox/next-international-app-router-forked-9mg42f?file=%2Fapp%2F%5Blocale%5D%2Fclient%2Fpage.tsx%3A10%2C1-10%2C40)
2. Type`/ua/client` url (like in screenshot below).

**Expected behavior**
Plural translations should be same on both server and client. 

**About**
next-international version: `1.1.3`
Next.js version: `14.0.1`

**Video**
https://github.com/QuiiBz/next-international/assets/32720808/89b4c9aa-8abb-4834-b2c2-01546a03f11e

**Screenshots**
<img width="1276" alt="image" src="https://github.com/QuiiBz/next-international/assets/32720808/865ae142-58af-46f4-9dfb-0910b79cb540">

**Comment by QuiiBz** [comment]
What's your browser? I suspect this is due to a difference in the `Intl.PluralRules` API across engines.

Here's a test with Firefox, Safari & Chrome and I can't reproduce the bug:
![Screenshot 2023-11-07 at 10 39 27](https://github.com/QuiiBz/next-international/assets/43268759/ab0fb777-977b-487b-a563-8c270fa95ced)

**Comment by nikitastryuk** [comment]
> What's your browser? I suspect this is due to a difference in the `Intl.PluralRules` API across engines.
> 
> Here's a test with Firefox, Safari & Chrome and I can't reproduce the bug: ![Screenshot 2023-11-07 at 10 39 27](https://user-images.githubusercontent.com/43268759/280990573-ab0fb777-977b-487b-a563-8c270fa95ced.png)

Thanks for quick response! I'm using latest chrome. 

Could you try `ua` locale, please? It seems to be working fine for `en`.

**Comment by QuiiBz** [comment]
Thanks for fixing the sandbox link. Indeed the issue isn't related to the browser, but that the backend's `Intl.PluralRule` instance uses a different locale (prob `en`) than the frontend's `Intl.PluralRule` instance (`ua`).

**Comment by nikitastryuk** [comment]
> Thanks for fixing the sandbox link. Indeed the issue isn't related to the browser, but that the backend's `Intl.PluralRule` instance uses a different locale (prob `en`) than the frontend's `Intl.PluralRule` instance (`ua`).

Just to clarify, you was able to reproduce it as well, right?

**Comment by QuiiBz** [comment]
Yeah I was able to reproduce with the steps you mentioned, I'll take a look asap to fix it at the package-level.

**Comment by nikitastryuk** [comment]
UPD after some debugging and investigation:

It started working with `uk` instead of `ua`. Looks like `Intl.PluralRules` works with codes from this [list](https://www.unicode.org/cldr/charts/43/supplemental/language_plural_rules.html) only. Not really obvious. 

But still not sure why server side initial result is different.

**Comment by QuiiBz** [comment]
I just tried and I'm not able to reproduce the bug with the provided CodeSandbox, with `en` as my default browser language or `ua`. Both `/en/client` & `/ua/client` pages works fine. I'm also using Chrome.

**Comment by nikitastryuk** [comment]
Issue also exists in `next-intl` - they say it's env problem.
https://github.com/amannn/next-intl/issues/605

Closing this since it's not a pckg issue. Thanks for your support!
