### ISSUE TITLE
A resulable function that could be run on serverSide helpers

### ISSUE THREAD

**Issue by Itsnotaka** [QuiiBz/next-international#283]
**Is your feature request related to a problem? Please describe.** 
I am still using /pages router, getServerSideProps is often used. This is the previous implementation when I am using `react-i18next`

```ts
/**
 * Initialize server-side rendering tRPC helpers.
 * Provides a method to prefetch tRPC-queries in a `getServerSideProps`-function.
 * Automatically prefetches i18n based on the passed in `context`-object to prevent i18n-flickering.
 * Make sure to `return { props: { trpcState: ssr.dehydrate() } }` at the end.
 */
export async function ssrInit(context: GetServerSidePropsContext) {
  const { serverSideTranslations } = await import(
    "next-i18next/serverSideTranslations"
  );
  const ctx = await createTRPCContext(context);
  const locale = getLocaleFromHeaders(context.req);

  const i18n = await serverSideTranslations(
    getLocaleFromHeaders(context.req),
    ["common"],
    i18nConfig,
  );

  const ssr = createServerSideHelpers({
    router: appRouter,
    transformer,
    ctx: { ...ctx, locale, i18n },
  });

  await ssr.viewer.public.i18n.prefetch();

  return ssr;
}
```

And this is the current implementation after switching.

```ts
export async function ssrInit(context: GetServerSidePropsContext) {
  const ctx = await createTRPCContext(context);
  const locale = getLocaleFromHeaders(context.req);

  const ssr = createServerSideHelpers({
    router: appRouter,
    transformer,
    ctx: { ...ctx, locale },
  });

  await ssr.viewer.public.i18n.prefetch();

  return ssr;
}
```
AS you can see, the removal of code is good. However, I have to put getLocaleProps in every getServerSideProps/getStaticProps which is not a good solution since I might forget to add such a function and the translation breaks.

**Describe the solution you'd like**
A `getServerSideTranslation` hook which could be used as a function that replaces getLocaleProps

**Comment by QuiiBz** [comment]
Unfortunately, `getLocaleProps` is mandatory if you want SSG/SSR, there's no way to load that data in the pages router otherwise than with `getServerSideProps` or `getStaticProps`
