### ISSUE TITLE
Translation extraction

### ISSUE THREAD

**Issue by rafae2k** [QuiiBz/next-international#285]
**Is your feature request related to a problem? Please describe.**
Is there a way to extract missing translations? 

Ex: I have translated a key in english but is missing in spanish etc

**Comment by QuiiBz** [comment]
You can use the `fallbackLocale` option in both `createI18nClient` / `createI18nServer` to automatically fallback to this locale if the current one is missing a key.

Example: https://github.com/QuiiBz/next-international/blob/8bb7f87268ccd77a189cb109abd78290f2cdd700/examples/next-app/locales/client.ts#L22
Documentation (probably needs to be improved for this option): https://next-international.vercel.app/docs/pages-setup#setup-provider

**Comment by rafae2k** [comment]
I mean something like that:

https://www.i18next.com/how-to/extracting-translations

**Comment by QuiiBz** [comment]
Sorry for misunderstand your question. We have a `defineLocale` helper that you can use to wrap your locales in: https://github.com/QuiiBz/next-international/blob/e4acd2fdf3c6ec181e218df82477f05df90c7311/examples/next-app/locales/fr.ts#L1

```ts
export default defineLocale({
  hello: 'World',
  ...
})
```
