### ISSUE TITLE
Types for variables that are equal to functions created from from createI18nClient or createI18nServer hooks

### ISSUE THREAD

**Issue by GovanO** [QuiiBz/next-international#286]
P.s. haven't found types I need in your library thus creating this ticket.

Current problem:

As a developer I would like to have types for all the functions created using createI18nClient or createI18nServer hooks. Those functions are:
1) useI18n/getI18n
2) useScopedI18n/getScopedI18n
3) I18nProviderClient/getStaticParams
4) useCurrentLocale/getCurrentLocale

In my case when I have my const t() = useI18n()  and I insert variable into t() function that is not an actual string ('"") key taken from my own i18n file but dynamically evaluates to the particular key from my i18n object - (example t(someDynamicallyEvaluateVariable) ) - typescript errors in such way:

![type inference failure](https://github.com/QuiiBz/next-international/assets/74191260/8086fb45-6f69-4b32-9068-86e73d5656e0)

Well, than I tried to infer the type of t() using syntax const t: typeof useI18n = useI18n() but it still errors in the way shown below:

![type inference failure 2](https://github.com/QuiiBz/next-international/assets/74191260/23eacc70-a8ad-4732-a98a-7e7a33bf7518)

Desired solution:

There are types provided for previously mentioned functions so that I as a developer don't have to set type of t() function to ": any" in order to satisfy typescript compiler. Such solution would also benefit me as a developer to show IntelliSense options as at the given moment I lose such benefit when setting function's type to :  ":  any".

Thanks in advance.

**Comment by QuiiBz** [comment]
The issue in your case seems to be that `item.question` isn't a literal type (e.g. `"how.it.works"`), but instead a `string`. I can't really help more without the code, but usually it can often be solved by using `as const` to the an object, or manually casting the variable to a locale key.

We also have a package that exports the types used by next-international, but I don't think you need this: https://github.com/QuiiBz/next-international/tree/main/packages/international-types

**Comment by GovanO** [comment]
Thank you for quick answer. I will try to see if international-types library will be of any help. 
And answering your wondering - yes, question is of type string but I give it value of actual key that exists on my localization object and set its type in such manner:

![question type](https://github.com/QuiiBz/next-international/assets/74191260/edb12240-8928-4f2f-9bc3-74c411ca4980)

But with this tsc compiler is showing the explanation mentioned in my initial comment. Am I doing the correct intent to make it work?

**Comment by QuiiBz** [comment]
You just need `as const` after your `questions` variable declaration in this case:

```ts
const questions = [
  {
    ..
  }
] as const
```

**Comment by GovanO** [comment]
Hm, tried but same tsc compiler error persists. Will try to play with types. Anyway - thank you a lot for a really fast feedback. I do appreciate it

**Comment by QuiiBz** [comment]
Feel free to share the code / a minimal reproduction so I can show you directly how to fix these kind of errors.
