### ISSUE TITLE
Is it possible to interpolate translation strings with more complex components?

### ISSUE THREAD

**Issue by chris-gil-martins** [QuiiBz/next-international#287]
I see that it is possible to replace params with values wrapped in components like so:

```js
const i18nStrings = {
    "hello": "Hello {name}"
}

{t('hello', {
    name: <strong>John</strong>,
 })}
```

Would it be possible to have interpolation without replacing params when needing to use more complex components or breaking up a string into different parts like so:

```jsx
const i18nStrings = {
    "hello": "Hello <1>World</1>"
}

<Interpolate t="hello">Hello <span className="custom-class">World</span></Interpolate>
```

**Comment by QuiiBz** [comment]
I'm not sure to understand why this `Interpolate` component is necessary. You can achieve the same by nesting multiple `t()`:

```ts
export default {
    hello: 'Hello {content}',
	world: 'World'
} as const

{t('hello', {
    name: <strong>{t('world')}</strong>
 })}
```

Could that help for your use-case? If not, could you explain why you'd need an `Interpolate` component?

**Comment by chris-gil-martins** [comment]
Ah good point, did not think about nesting multiple `t()`'s. This should cover the needed cases. Thanks!
