### ISSUE TITLE
Need call one time I18nProviderClient for all client component

### ISSUE THREAD

**Issue by thainv92** [QuiiBz/next-international#291]
**Is your feature request related to a problem? Please describe.**
- I follow docs about use translation for Client Components must use I18nProviderClient. And must wrap each client component in each I18nProviderClient with custom hocs, which very much time as below.
+ my hocs withI18nProviderClient
![image](https://github.com/QuiiBz/next-international/assets/133634759/8ec0f0e9-8f42-4089-ae6b-1195678b215a)
+ my component (.../src/components/Layout/Navbar/UserDropDown.tsx)
![image](https://github.com/QuiiBz/next-international/assets/133634759/8849b175-fee5-4b64-8d75-b730fee21f5c)
- Your example only helpful for group page client, which not valid for component folder [https://github.com/QuiiBz/next-international/blob/main/examples/next-app/app/%5Blocale%5D/client/page.tsx](url)

**Describe the solution you'd like**
I expect only wrapper only one place and call use translation for any client component

**Comment by QuiiBz** [comment]
I wouldn't recommend to use this pattern. Instead, you should have a single `I18nProviderClient` at the root of your application: https://github.com/QuiiBz/next-international/blob/main/examples/next-app/app/%5Blocale%5D/provider.tsx

**Comment by thainv92** [comment]
Yes, I've tried applying it, and it works for me. However, there's a slight delay when refreshing the page.
Will the delay time be longer as the language file gets bigger?

**Comment by QuiiBz** [comment]
You can use the `fallback` prop in `I18nProviderClient` to show a fallback while loading the locale client-side: https://github.com/QuiiBz/next-international/blob/8bb7f87268ccd77a189cb109abd78290f2cdd700/examples/next-app/app/%5Blocale%5D/provider.tsx#L13

If your page is static and uses `generateStaticParams`, you won't have any loading state.
