### ISSUE TITLE
How to infer useScopedI18n type?

### ISSUE THREAD

**Issue by ImamAlfariziSyahputra** [QuiiBz/next-international#297]
I made type like this below, the question is, am i correct? 
<img width="391" alt="image" src="https://github.com/QuiiBz/next-international/assets/63343105/3026cc95-1f8d-416d-a635-dac42d7afb8e">

then I got the correct types:
<img width="425" alt="image" src="https://github.com/QuiiBz/next-international/assets/63343105/87b69e3a-450e-473c-a69c-76e47d9d7656">

but if I scoped other than `yup` it does not give me type error
<img width="350" alt="image" src="https://github.com/QuiiBz/next-international/assets/63343105/c43d58c1-f040-4227-94ac-9f95b61aa88d">

here is my `en.ts` file:
<img width="492" alt="image" src="https://github.com/QuiiBz/next-international/assets/63343105/48692a50-b1e5-4e67-8486-9cc2426460c1">

**Comment by QuiiBz** [comment]
Could you share a reproduction with the code?

**Comment by QuiiBz** [comment]
Closing as stale.
