### ISSUE TITLE
Config rewrites not working 

### ISSUE THREAD

**Issue by thainv92** [QuiiBz/next-international#301]
**Describe the bug**
Rewrites config working when use middleware next-international

**To Reproduce**
Your demo: https://codesandbox.io/p/devbox/next-international-app-router-forked-j9wq2k?file=%2Fpackage.json%3A17%2C4-18%2C36
1. add config
```ts
/** @type {import('next').NextConfig} */
const nextConfig = {
  async rewrites() {
    return [
      {
        source: "/blog",
        destination: "https://example.com/blog",
      },
      {
        source: "/blog/:slug",
        destination: "https://example.com/blog/:slug", // Matched parameters can be used in the destination
      },
    ];
  },
};

module.exports = nextConfig;
```
2. Go to: https://j9wq2k-3000.csb.app/en/blog
3. Error display

**Expected behavior**
Working rewrite well

**About (please complete the following information):**
 - "next": "13.5.4",
 - "next-international": "^1.1.4"

**Comment by navata** [comment]
@QuiiBz  I really hope to receive support from your reply.

**Comment by QuiiBz** [comment]
Sorry for the delay, I started a new job recently. You have to update the `source` field to take into account the `locale` dynamic param:

```ts
/** @type {import('next').NextConfig} */
const nextConfig = {
  async rewrites() {
    return [
      {
        source: "/:locale/blog",
        destination: "https://example.com/blog",
      },
      {
        source: "/:locale/blog/:slug",
        destination: "https://example.com/blog/:slug", // Matched parameters can be used in the destination
      },
    ];
  },
};
```

I've tested it [here](https://codesandbox.io/p/devbox/next-international-app-router-forked-j9wq2k?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clqdod5w200053b6g4iuy6ukr%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clqdod5w100023b6g2i2wku4g%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clqdod5w100033b6gkzyl1j8p%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clqdod5w100043b6gypgarqzk%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B60%252C40%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clqdod5w100023b6g2i2wku4g%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqdod5w100013b6gntmnpbl2%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clqdod5w100023b6g2i2wku4g%2522%252C%2522activeTabId%2522%253A%2522clqdod5w100013b6gntmnpbl2%2522%257D%252C%2522clqdod5w100043b6gypgarqzk%2522%253A%257B%2522id%2522%253A%2522clqdod5w100043b6gypgarqzk%2522%252C%2522activeTabId%2522%253A%2522clqdofc0q005u3b6gtmgd4s89%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522id%2522%253A%2522clqdofc0q005u3b6gtmgd4s89%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252Fen%2522%257D%255D%257D%252C%2522clqdod5w100033b6gkzyl1j8p%2522%253A%257B%2522id%2522%253A%2522clqdod5w100033b6gkzyl1j8p%2522%252C%2522activeTabId%2522%253A%2522clqdof806004u3b6gef0w28om%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522clqdof806004u3b6gef0w28om%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D) and it's working as expected when navigating to `/en/blog` or `/blog` directly.
