### ISSUE TITLE
`useI18n` hook very slow, performance depends on translation file size

### ISSUE THREAD

**Issue by finkrer** [QuiiBz/next-international#302]
**Describe the bug**
I am now in the process of migrating a large application away from `next-translate` to `next-international` (well, at least I'm trying it out, looks cool). I have noticed that the app is significantly slower this way.

After using the React profiler, I have confirmed that renders now take about 300 ms instead of 70 ms, in particular because of small components (like badges) taking a lot of time to render.

After some quick and dirty profiling, here's how long it takes to run my app's global context hook that I use to retreive the current locale and this package's `useI18n` hook:
 
```
intl-utils.ts:77 useIntl useUserContext: 0.001953125 ms
intl-utils.ts:80 useIntl useI18n: 0.843017578125 ms
intl-utils.ts:77 useIntl useUserContext: 0.001953125 ms
intl-utils.ts:80 useIntl useI18n: 0.85205078125 ms
intl-utils.ts:77 useIntl useUserContext: 0.001953125 ms
intl-utils.ts:80 useIntl useI18n: 0.783935546875 ms
intl-utils.ts:77 useIntl useUserContext: 0.0009765625 ms
intl-utils.ts:80 useIntl useI18n: 0.85302734375 ms
intl-utils.ts:77 useIntl useUserContext: 0.001953125 ms
intl-utils.ts:80 useIntl useI18n: 0.828125 ms
intl-utils.ts:77 useIntl useUserContext: 0.002197265625 ms
intl-utils.ts:80 useIntl useI18n: 0.81982421875 ms
intl-utils.ts:77 useIntl useUserContext: 0.0029296875 ms
intl-utils.ts:80 useIntl useI18n: 0.938232421875 ms
```
Sure enough, every time I run the `useI18n` hook, it takes about 1 ms. Mutiply that by like 12 strings per card, 40 cards per list render, and we've got a performance problem.

After taking a look at the code, I have found this:
https://github.com/QuiiBz/next-international/blob/e4acd2fdf3c6ec181e218df82477f05df90c7311/packages/next-international/src/common/create-t.ts#L26-L29

Surely this is O(n) in respect to the translation file size... Every time I use the hook? This cannot be good for performance.

Now, this is on you of course, but I would expect this work to be performed when creating the hook, not when using it. The values that the hooks return should probably just be kept in the context and retrieved when the hooks are used. That is, `t` should just be in `I18nClientContext`, not created every time with `createT`.

For reference, my translations file is 138 KB (support for separate files for separate pages would be great).

Another reference is that `next-translate`'s hook works no slower than 0.08 ms, and routinely finishes in 0.02 ms.

**Update**: I have put the `t` value in a context myself. Here are the performance numbers:

```
intl-utils.ts:79 useIntl useUserContext: 0.006103515625 ms
intl-utils.ts:82 useIntl useI18n: 0.003662109375 ms
intl-utils.ts:79 useIntl useUserContext: 0.001953125 ms
intl-utils.ts:82 useIntl useI18n: 0.003173828125 ms
intl-utils.ts:79 useIntl useUserContext: 0.0009765625 ms
intl-utils.ts:82 useIntl useI18n: 0.001953125 ms
intl-utils.ts:79 useIntl useUserContext: 0.002197265625 ms
intl-utils.ts:82 useIntl useI18n: 0.001953125 ms
intl-utils.ts:79 useIntl useUserContext: 0.00390625 ms
intl-utils.ts:82 useIntl useI18n: 0.0029296875 ms
```
Would be great to have this performance out of the box.

**To Reproduce**
1. Have a huge translations file
2. I bet it's gonna be slow as well

**Expected behavior**
The hook works fast

**About (please complete the following information):**
 - next-international 1.1.4
 - Next.js version 14.0.3

**Comment by QuiiBz** [comment]
Sorry for the delay, I started a new job. I think we just need to cache the result, which I don't know yet wasn't done yet.
