### ISSUE TITLE
Is it possible to add support for namespaces like in i18next?

### ISSUE THREAD

**Issue by 1Mouse** [QuiiBz/next-international#308]
ref: https://www.i18next.com/principles/namespaces

namespaces allow us to have separate files for each page, is this possible with your library?
Thanks in advance

**Comment by salmanorak** [comment]
@1Mouse , I think You can create namespaces in current feature set. 

```typescript
const ns1: {
  key1: 'value1',
  key2: 'value2'
} as const

const ns2: {
  key1: 'value1',
  key2: 'value2'
} as const

export default {
 ns1,
 ns2
}

```

then When You are going to use it

```typescript

 const t = useI18n()
 ...
 const content = t(ns1.key1)
 
```

if You want You can create separate files for different name spaces and import them to index.ts.

**Comment by 1Mouse** [comment]
fantastic thanks for your help
