### ISSUE TITLE
T function reference is not stable between renders.

### ISSUE THREAD

**Issue by salmanorak** [QuiiBz/next-international#309]
**Describe the bug**
The reference of t function that returns from useI18n and useScopedI18n is not stable. 

**To Reproduce**
[reproduce:](https://codesandbox.io/p/devbox/unstable-t-hqxhf9)

**Expected behavior**
The reference of the t function should be stable so it will not cause a re-calculate when it is used in any hook dependency array.

**Screenshots**
after each re-render the useEffect that has only t function dependency is refiring.
![image](https://github.com/QuiiBz/next-international/assets/41747037/cbd03b75-0f09-4a4a-ae4c-8cb86d97dac5)

**About (please complete the following information):**
 - next-international version [1.1.4]
 - Next.js version [e.g. 14.0.1]

**Workaround**

For know I have wrapped the function with one useState hook.

```typescript
import { useState } from 'react';
import { useI18n } from '@/locale';

export const useTranslate = () => {
  const [t] = useState<ReturnType<typeof useI18n>>(() => useI18n());

  return t;
};

```

**Comment by salmanorak** [comment]
@QuiiBz  thansk for fix. When You are planing the release with fixes?

**Comment by QuiiBz** [comment]
I'd like to merge https://github.com/QuiiBz/next-international/pull/316 that fixes another issue before landing a new release.

**Comment by QuiiBz** [comment]
Sorry for the delay - https://github.com/QuiiBz/next-international/releases/tag/1.2.0 has been published!
