### ISSUE TITLE
Can't set an empty string as translation value for a key

### ISSUE THREAD

**Issue by alienzhangyw** [QuiiBz/next-international#311]
In your code, if value is falsy, then it will be the key string. But what if the value should be `''` in some circumstances?

https://github.com/QuiiBz/next-international/blob/e4acd2fdf3c6ec181e218df82477f05df90c7311/packages/next-international/src/common/create-t.ts#L65-L70

For example, I need to set different colors for the spans below: 
```html
<h1>
  <span className="red">{t('span1')}</span>
  <span className="green">{t('span2')}</span>
  <span className="red">{t('span3')}</span>
</h1>
```
In different languages, the content of `t('span1')` or `t('span3')` may be empty `''`. But you turned it into `'span1'` or `'span3'`.

**Comment by QuiiBz** [comment]
Do you have a use-case in mind for a value that could be an empty string? Happy to re-open if so.

**Comment by alienzhangyw** [comment]
> Do you have a use-case in mind for a value that could be an empty string? Happy to re-open if so.

I can use `'\u200B'` instead, never mind.

**Comment by TimurKr** [comment]
Hey. I just spent 15 minutes trying to find this conversation that would solve this issue for me. I don't really see the point in replacing an empty string with the key of the translation. Is there any? Seems to me that an empty string is simply an empty string, why forbid the users from using it in their translations? Using `'\u200B'` seems like a quick fix to a problem that shouldn't exist. 

My use-case is this: I have a formatted headline, where one word in the middle should be different color and the last two words should not separate. My solution for this is:

```ts
export default {
  headline: {
    start: 'This is a',
    highlight: 'headline',
    middle: 'that is',
    end: 'nicely formated',
  },
}
```

and in the code

```tsx
<h2 className={styles.headline}>
  {tr('start')}{' '}
  <span className={styles.headlineHighlight}>{tr('highlight')}</span>{' '}
  {tr('middle')} <span className={styles.nowrap}>{tr('end')}</span>
</h2>
```

This already seems like an ugly solution to something pretty simple (if you have ideas on how to do this in a cleaner way, I am listening). But now think of other languages. Some might have the highlighted word in the front => the start needs to be empty. Some might be short enough not to use the `<span className="no-wrap">` at all => `end` should be empty. Using `\u200b` seems wrong for this use-case.

What are your thoughts?

**Comment by alienzhangyw** [comment]
> Hey. I just spent 15 minutes trying to find this conversation that would solve this issue for me. I don't really see the point in replacing an empty string with the key of the translation. Is there any? Seems to me that an empty string is simply an empty string, why forbid the users from using it in their translations? Using `'\u200B'` seems like a quick fix to a problem that shouldn't exist.
> 
> My use-case is this: I have a formatted headline, where one word in the middle should be different color and the last two words should not separate. My solution for this is:
> 
> ```ts
> export default {
>   headline: {
>     start: 'This is a',
>     highlight: 'headline',
>     middle: 'that is',
>     end: 'nicely formated',
>   },
> }
> ```
> 
> and in the code
> 
> ```tsx
> <h2 className={styles.headline}>
>   {tr('start')}{' '}
>   <span className={styles.headlineHighlight}>{tr('highlight')}</span>{' '}
>   {tr('middle')} <span className={styles.nowrap}>{tr('end')}</span>
> </h2>
> ```
> 
> This already seems like an ugly solution to something pretty simple (if you have ideas on how to do this in a cleaner way, I am listening). But now think of other languages. Some might have the highlighted word in the front => the start needs to be empty. Some might be short enough not to use the `<span className="no-wrap">` at all => `end` should be empty. Using `\u200b` seems wrong for this use-case.
> 
> What are your thoughts?

Your case is really close to mine. I needed to highlight some keywords in a sentence, while in chinese the keywords may locate at the start or the end. Since this project do not support interploration with jsx like [react-i18next](https://react.i18next.com/latest/trans-component), I had to split the sentence into spans and make some parts empty.
