### ISSUE TITLE
New importLocale prop for I18nProviderClient missing on documentation

### ISSUE THREAD

**Issue by maloyuso** [QuiiBz/next-international#327]
**Describe the bug**
A new required prop was added to I18nProviderClient but there's no documentation on whats the expected value. Also useScopedI18n stops working. 

**To Reproduce**
1. Mounting <I18nProviderClient locale={locale}>
2. An error is raised: Property 'importLocale' is missing in type '{ children: Element; locale: "en"; fallback: Element; }' but required in type '{ locale: string; fallback?: ReactNode; importLocale: Promise<Record<string, unknown>>; children: ReactNode; }
3. useScopedI18n stops working. The passed scope is not being recognized

**Expected behavior**
There's no error on I18nProviderClient and useScopedI18n works as expected.

**Screenshots**
NA

**About (please complete the following information):**
 - next-international version 1.2.0
 - Next.js version 14.0.1

**Additional context**
Issue when trying to update to next-international version 1.2.0

**Comment by QuiiBz** [comment]
https://github.com/QuiiBz/next-international/releases/tag/1.2.1 was released to fix the types.
