### ISSUE TITLE
`I18nProviderClient` throwing `importLocale` prop as required

### ISSUE THREAD

**Issue by ubinatus** [QuiiBz/next-international#330]
**Describe the bug**
Usage of `I18nProviderClient` is throwing a type error, requesting a prop that is not needed.

**To Reproduce**
1. Go to the examples/next-app
2. Open the /examples/next-app/app/[locale]/provider.tsx
3. Typescript server showing error on `I18nProviderClient` requesting to pass `importLocale` prop.

**Expected behavior**
Provider should not request for `importLocale`, only `locale` and optional `fallback` belongs to the interface as stated on the [app-setup docs](https://next-international.vercel.app/docs/app-setup#move-your-existing-files) 

**Screenshots**
<img width="1054" alt="image" src="https://github.com/QuiiBz/next-international/assets/51177379/63dde3a0-0d54-493c-9e42-3e8466f243fe">

**About (please complete the following information):**
 - next-international version: v1.2.1
 - Next.js version: v14.0.4

**Comment by ubinatus** [comment]
Working on to close this issue

**Comment by QuiiBz** [comment]
Released in https://github.com/QuiiBz/next-international/releases/tag/1.2.2
