### ISSUE TITLE
[1.2.2] Internal error: ReferenceError: use is not defined

### ISSUE THREAD

**Issue by ApacheEx** [QuiiBz/next-international#332]
**Describe the bug**
It looks like this [PR](https://github.com/QuiiBz/next-international/pull/331) removed `use` from the import, right now I get the error:

```

 ⨯ node_modules/next-international/dist/app/client/index.js (77:67) @ _a
 ⨯ Internal error: ReferenceError: use is not defined
    at I18nProvider (./node_modules/next-international/dist/app/client/index.js:77:72)
```

**Comment by QuiiBz** [comment]
Released in https://github.com/QuiiBz/next-international/releases/tag/1.2.3, thanks!
