### ISSUE TITLE
How to use translation outside of components? I have some special circumstances where I need to use translation outside of the component. Is there a compatible method to use translation outside of the component? Although it is troublesome and terrible, I still need to consider this situation.

### ISSUE THREAD

**Issue by hqw567** [QuiiBz/next-international#334]
Related Discussions:https://github.com/amannn/next-intl/discussions/729

**Comment by damianricobelli** [comment]
@hqw567 Could you show us an example of the use case you are facing so we can understand a bit more?

Maybe what you need is to use the next-international core to build your own i18n type-safe function? --> https://github.com/QuiiBz/next-international/tree/main/packages/international-types

@QuiiBz if my suggestion is not correct, please let me know
