### ISSUE TITLE
`useI18n` must be used inside `I18nProvider`

### ISSUE THREAD

**Issue by Fionn96** [QuiiBz/next-international#335]
I have a client component that needs to be used in the server page. When I try to import it directly, I get the error "Error: `useI18n` must be used inside `I18nProvider`". How to solve it?

[codesandbox](https://codesandbox.io/p/devbox/next-international-app-router-forked-wjfq23?embed=1&file=%2Fapp%2F%5Blocale%5D%2Fpage.tsx&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clr9b0g3z00073j6gkil4n08s%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clr9b0g3z00023j6gvkv4tx4h%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clr9b0g3z00043j6gbpshky23%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clr9b0g3z00063j6g0jnav2ii%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clr9b0g3z00023j6gvkv4tx4h%2522%253A%257B%2522id%2522%253A%2522clr9b0g3z00023j6gvkv4tx4h%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clr9b0g3z00013j6gyqzfczhl%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clr9b0g3z00013j6gyqzfczhl%2522%257D%252C%2522clr9b0g3z00063j6g0jnav2ii%2522%253A%257B%2522id%2522%253A%2522clr9b0g3z00063j6g0jnav2ii%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clr9b0g3z00053j6gtc2kh2jj%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522path%2522%253A%2522%252Fen%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clr9b0g3z00053j6gtc2kh2jj%2522%257D%252C%2522clr9b0g3z00043j6gbpshky23%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clr9b0g3z00033j6gqu4ykjxe%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%255D%252C%2522id%2522%253A%2522clr9b0g3z00043j6gbpshky23%2522%252C%2522activeTabId%2522%253A%2522clr9b0g3z00033j6gqu4ykjxe%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by QuiiBz** [comment]
You need to wrap client components inside `I18nClientProvider`, as the error message suggests. In your codesandbox you're doing it for the `/client` page inside the `layout.tsx`, so you can just move the layout from `/app/[locale]/client/layout.tsx` to `/app/[locale]/layout.tsx`.

**Comment by emporteme** [comment]
> You need to wrap client components inside `I18nClientProvider`, as the error message suggests. In your codesandbox you're doing it for the `/client` page inside the `layout.tsx`, so you can just move the layout from `/app/[locale]/client/layout.tsx` to `/app/[locale]/layout.tsx`.

could you share a code structure?
