### ISSUE TITLE
fallbackLocale type mismatch for nested locale style

### ISSUE THREAD

**Issue by bastibuck** [QuiiBz/next-international#344]
**Describe the bug**
When using a `fallbackLocale` with the pages-router like described [in the docs](https://next-international.vercel.app/docs/pages-setup#setup-provider) TypeScript doesn't like if you are using the nested style of locales. Flat keys works fine.

**To Reproduce**
1. Follow setup instructions and use a nested locale file e.g.
```ts
const en = {
  hello: {
    world: 'Hello, World!',
    user: 'Hello, {name}!',
  },
} as const;

export default en;
``` 

2. Use the locale as `fallbackLocale` in `_app.tsx`
3. See error

**Expected behavior**
It should not throw an error regardless of using nested or flat style.

**Additional context**
It does work with the flat style of locale e.g.
```ts
const en = {
  'hello.world': 'Hello, World!',
  'hello.user': 'Hello, {name}!',
} as const;

export default en;
```

**Comment by QuiiBz** [comment]
Fix released in https://github.com/QuiiBz/next-international/releases/tag/1.2.4!
