### ISSUE TITLE
[Question] How do I translate text that is indirectly a client component?

### ISSUE THREAD

**Issue by akmalmzamri** [QuiiBz/next-international#347]
Some of my client components import text from separate files. The text is defined separately to keep things organised. 

config/nav.ts
```
export const defaultLinks: SidebarLink[] = [
  { href: "/", title: "Home", icon: HomeIcon },
  { href: "/account", title: "Account", icon: Cog },
  { href: "/settings", title: "Settings", icon: Cog },
]
```

components/NavBar.tsx
```
"use client"

export default function Navbar() {
  const [foo, setFoo] = useState(false)
  ...other stuff
  {defaultLinks.map((link) => (...)}
}
```

Is there a way to translate the text inside `config/nav.ts`? I can't use `getI18n` as it is imported by a client component. I can't use `useI18n` as it is not inside a React function.

Should I change the code design? If yes, what is the common pattern to handle this kind of translation?

I guess turning the config into a function and passing the translator function works, but I would lose the type safety
```
"use client"

export default function Navbar() {
  const t = useScopedI18n("nav.sidebar")
  const [foo, setFoo] = useState(false)
  ...other stuff
  {getDefaultLinks(t).map((link) => (...)}
}
```

**Comment by QuiiBz** [comment]
Instead of storing the translation inside `title` (e.g. `"Home"`, `"Account"` ...), you could store the *key* and then use it inside your component when you `map()`, since you have access to `useI18n` / `useScopedI18n` there.

Let me know if that didn't help you enough, and I can try to send an example.

**Comment by akmalmzamri** [comment]
Yes that should work. Thanks!

**Comment by akmalmzamri** [comment]
## Update: Here's my solution

A bit convoluted, but it gives me what I need:

- A way to define the locale key with auto-complete feature
- No error on the translate function

Step 1: create a type for the possible locale keys
```
import locale from "@/locales/en"

type Path<T> = T extends object
  ? {
      [K in keyof T]: K extends string
        ? T[K] extends string
          ? `${K}`
          : T[K] extends object
            ? `${K}.${Path<T[K]>}`
            : never
        : never
    }[keyof T]
  : ""

// Type of the paths based on the 'locale' object
export type LocaleKey = Path<typeof locale>
```

Step 2: Create a helper function to help us define the key, and that takes an auto-completable locale path as the param, and returns the same value with the string literal type preserved
```
export function localeKey<T extends LocaleKey>(path: T): T {
  return path
}
```

Step 3: Use it like this
```
export const defaultLinks: SidebarLink[] = [
  { title: localeKey("hello") },
  { title: localeKey("hello.world") },
]
```

Is there a better way to do this?

**Comment by QuiiBz** [comment]
This solution works but seems a bit complex, we should be able to re-use types from [`international-types`](https://github.com/QuiiBz/next-international/tree/main/packages/international-types)

**Comment by hmssameer55** [comment]
> Instead of storing the translation inside `title` (e.g. `"Home"`, `"Account"` ...), you could store the _key_ and then use it inside your component when you `map()`, since you have access to `useI18n` / `useScopedI18n` there.
> 
> Let me know if that didn't help you enough, and I can try to send an example.

//Can u please send an example for this
