### ISSUE TITLE
error - SerializableError: Error serializing `.locale["pages.past.date"]` returned from `getServerSideProps` in "/".

### ISSUE THREAD

**Issue by noxify** [QuiiBz/next-international#35]
Hey,

i'm currently creating a simple example to test the new blitz toolkit.

At the same time I want to test your i18n package.

Everything seems to work, but since I added the language switcher and refreshed the page after changing the language from "en" (=default) to "de" I get the following error:

```
error - SerializableError: Error serializing `.locale["pages.past.date"]` returned from `getServerSideProps` in "/".
Reason: `undefined` cannot be serialized as JSON. Please use `null` or omit this value.
    at isSerializable (<local_path>/node_modules/next/dist/lib/is-serializable-props.js:36:19)
    at <local_path>/node_modules/next/dist/lib/is-serializable-props.js:43:66
    at Array.every (<anonymous>)
    at isSerializable (<local_path>/node_modules/next/dist/lib/is-serializable-props.js:40:39)
    at <local_path>/node_modules/next/dist/lib/is-serializable-props.js:43:66
    at Array.every (<anonymous>)
    at isSerializable (<local_path>/node_modules/next/dist/lib/is-serializable-props.js:40:39)
    at Object.isSerializableProps (<local_path>/node_modules/next/dist/lib/is-serializable-props.js:63:12)
    at Object.renderToHTML (<local_path>/node_modules/next/dist/server/render.js:552:67)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  page: '/'
}
```

To be honest, I'm not sure if this is a problem with your package.

You can find the complete source here: https://github.com/noxify/blitz-hackernews

----

Steps to reproduce:

1. Install the app 
2. Start the dev server via `npm run dev`
3. Open the browser and go to page http://localhost:3000
   * You will see the index page and the language is english
4. Switch the language to de (=german) ( via the icon in the header navigation )
   * You will see that the language has been changed to german
5. Reload the page
   * You will see the error

----

Please let me know in case you need additional information or something else.

**Comment by noxify** [comment]
i think I fixed it.

With the following changes, I was able to get it working:

https://github.com/noxify/blitz-hackernews/commit/2f26a51c2edf8025c9d6d491a62f984938b7e54f

Short version:
I moved the following code from the `pages/index.tsx` to `pages/_app.tsx`:

```
export const getServerSideProps = getLocaleProps()
```

**Comment by QuiiBz** [comment]
`_app` doesn't support `getServerSideProps` / `getStaticProps` (https://nextjs.org/docs/advanced-features/custom-app#caveats), so your locales are loaded client-side. Is this what you want to achieve?

**Comment by noxify** [comment]
hmm... good question - If it could be loaded server-side, it would be better.

Any thoughts how to solve it?

**Comment by QuiiBz** [comment]
You have to use `getLocaleProps` and assign it to `getServerSideProps` / `getStaticProps`. I'm not sure if the error above is due to next-international or Next.js.

**Comment by QuiiBz** [comment]
Could you provide a reproduction that doesn't use a database?

**Comment by noxify** [comment]
sure.

**Comment by noxify** [comment]
With a fresh installation, I wasn't able to reproduce it.

Tested it with a minimal setup --> Works as expected

Tested it then with a full app ( using SQLite ) --> Works as expected

here the link to the repo: https://github.com/noxify/blitz-international-issue

**Comment by noxify** [comment]
I have no clue what happened since yesterday - but I seems that everything is now working as expected ( undo my changes to enable server-side loading ) 

Anyway...But it's working now

**Comment by QuiiBz** [comment]
Happy to hear that it's resolved. Kinda strange, but I don't think the issue was coming from next-international.

**Comment by noxify** [comment]
i think it could be related with the "magic" from the blitz toolkit - or it was just user handling 😏

**Comment by noxify** [comment]
Finally...I got the issue.

I use `defineLocale` for the german translation ( `de.ts` ) and after changing the structure in the `en.ts`, VSC mentioned that the structure isn't valid and I added all missing values to the `de.ts` ( via Quick help in VSC ).

Unfortunately I forgot to translate one value:

```
  "pages.past.date": undefined,
```

And that's what the error is also saying 

```
...SerializableError: Error serializing `.locale["pages.past.date"]`...
Reason: `undefined` cannot be serialized as JSON. Please use `null` or omit this value.
```
