### ISSUE TITLE
bug: Not changing the already loaded translations

### ISSUE THREAD

**Issue by FleetAdmiralJakob** [QuiiBz/next-international#351]
**Describe the bug**
When using `useChangeLocal()` and call this on an onClick listener than the already loaded translations are not changing even if the locale change is visible in the url 

**To Reproduce**
Look at the preview deployment of this https://github.com/The-Creative-Programming-Group/Weather-App/pull/213 here: https://weather-app-git-move-to-next-830f94-creative-programming-group.vercel.app/settings and try to change the locale with the button

**Expected behavior**
All the texts change to the other language

**About (please complete the following information):**
 - next-international version 1.2.3
 - Next.js version 14.1.0

**Additional context**
I think the problem lays here: https://github.com/The-Creative-Programming-Group/Weather-App/blob/move-to-next-internationalization/apps/web/src/pages/settings/index.tsx

**Comment by Abbosbek-cloud** [comment]
There my [issue](https://github.com/QuiiBz/next-international/issues/346#issue-2121486391) is related to yours. I think the cause is caching the translations. 

If you find any solutions, let me know, please! I am looking for as well.

**Comment by FleetAdmiralJakob** [comment]
Thank you @Abbosbek-cloud I will look at the other issue and hope that this get fixed soon.

**Comment by FleetAdmiralJakob** [comment]
Is Duplicated
