### ISSUE TITLE
Custom hook for parsed useScopedI18n & useI18n

### ISSUE THREAD

**Issue by pavelsushkov** [QuiiBz/next-international#367]
Hello, while #343 is currently not possible, I'm thinking of a workaround.
Currently, I'm using this parser: https://www.npmjs.com/package/html-react-parser
and wrap every entry of t or scopedT like this

```js
parse(scopedT('specificKey', { specificKeyParam: 'paramValue' }
```

It's not clean and quite an unreliable approach, so I tried to make a custom hook. I want to return the same functions as useScopedI18n and useI18n, but parsed.

So far I got this and stuck with parameters of functions. What would be a proper way to declare them?

```js
'use client';

import type {
  FlattenLocale,
  LocaleKeys,
  ParamsObject,
  Scopes,
} from 'international-types';

import { useCurrentLocale, useI18n, useScopedI18n } from '@/../locales/client';
import type en from '@/../locales/en';

import parse from 'html-react-parser';

export type DefaultLocale = FlattenLocale<typeof en>;
type Scope = Scopes<DefaultLocale>;
type Key = LocaleKeys<DefaultLocale, Scope>;

export const useTranslation = (scope: Scopes<DefaultLocale>) => {
  const locale = useCurrentLocale();
  const unparsedScopedT = useScopedI18n(scope);
  const unparsedT = useI18n();

  const scopedT = (key: ???, params?: ???): ReturnType<typeof parse> => {
    return params 
      ? parse(unparsedScopedT(key, params))
      : parse(unparsedScopedT(key));
  }

  const t = (key: ???, ???): ReturnType<typeof parse> => {
    return parse(unparsedT(...));
  }

  return {
    locale,
    scopedT,
    t,
  }
}
```

**Comment by QuiiBz** [comment]
You can take a look at some examples here: https://github.com/QuiiBz/next-international/tree/main/packages/international-types

Let me know if you're still stuck on this, but I believe it should be pretty much the same.

**Comment by QuiiBz** [comment]
Feel free to send a minimal reproduction (e.g. CodeSandbox) so I can try to help you with the types!
