### ISSUE TITLE
Argument of type 'string' is not assignable to parameter of type 'never'.ts(2345)

### ISSUE THREAD

**Issue by nicitaacom** [QuiiBz/next-international#368]
I want to change language from 'en' to 'fr'

I use [this](https://next-international.vercel.app/docs/app-get-change-locale) guide

I expect that in this guide I can just ctrl+c ctrl+v and it will work with next.js 14

In fact I get this error `Argument of type 'string' is not assignable to parameter of type 'never'.ts(2345)`

Code I use to get error
**app/[locale]/client/page.tsx**
```tsx
'use client'

import { useI18n, useScopedI18n } from '../../locales/client'
import { useChangeLocale, useCurrentLocale } from '../../locales/client'

export function ClientPage () {

 const t = useI18n()
  const scopedT = useScopedI18n('hello')
   const changeLocale = useChangeLocale()
  const locale = useCurrentLocale()
  return (
    <div>
      <p>{t('hello')}</p>
 
      {/* Both are equivalent: */}
      <p>{t('hello.world')}</p>
      <p>{scopedT('world')}</p>
 
      <p>{t('welcome', { name: 'John' })}</p>
      <p>{t('welcome', { name: <strong>John</strong> })}</p>
       <>
      <p>Current locale: {locale}</p>
      <button onClick={() => changeLocale('en')}>English</button>
      <button onClick={() => changeLocale('fr')}>French</button>
    </>
    </div>
  )
}
```

<br/>

**app/locales/client.ts**
```ts
// locales/client.ts
"use client"
import { createI18nClient } from 'next-international/client'
 
export const { useI18n, useScopedI18n, I18nProviderClient } = createI18nClient({
  en: () => import('./en'),
  fr: () => import('./fr')
})
 

export const {
  useChangeLocale,
  useCurrentLocale,
  
} = createI18nClient({
  
})
```

**app/locales/server.ts**
```ts
// locales/server.ts
import { createI18nServer } from 'next-international/server'
 
export const { getI18n, getScopedI18n, getStaticParams } = createI18nServer({
  en: () => import('./en'),
  fr: () => import('./fr')
})

export const {
  getCurrentLocale,
  
} = createI18nServer({
  
})
```

Also in guide I see
```
export const {
  getCurrentLocale,
  ...
} = createI18nServer({
  ...
})
```
But if I keep `...` it will throw the error

<br/>

I expect that you send me MVP where internatiolazation work like
/ - english
/fr - french

for example
Because I don't want to have /en route for english language
I want to have / route for english language

**Comment by QuiiBz** [comment]
This is a totally unrelated thing, see the documentation that covers this feature: https://next-international.vercel.app/docs/app-middleware-configuration#rewrite-the-url-to-hide-the-locale

Inside your middleware, you have to use the `urlMappingStrategy` option as `rewrite` or `rewriteDefault` depending on what you want:

```ts
const I18nMiddleware = createI18nMiddleware({
  locales: ['en', 'fr'],
  defaultLocale: 'en',
  urlMappingStrategy: 'rewriteDefault' // or 'rewrite'
})
```

> I'm waiting for some minimal example I can just copy paste
We do have both an [example application](https://github.com/QuiiBz/next-international/tree/main/examples/next-app) and a [CodeSandbox](https://codesandbox.io/p/sandbox/jovial-paper-skkprk?file=%2Fapp%2F%5Blocale%5D%2Fpage.tsx%3A1%2C1) that you can refer too, along with the documentation.

**Comment by nicitaacom** [comment]
> ```ts
> rewriteDefault
> ```

https://github.com/QuiiBz/next-international/assets/39565703/423fb833-134a-43de-861d-3ea21e445ddc



As you see translation work only if I delete property you message me to set

Plese fix this issue

**Comment by QuiiBz** [comment]
CodeSandbox doesn't work correctly with middlewares (notably with cookies), do you have the same issue when running the code locally?

**Comment by nicitaacom** [comment]
> CodeSandbox doesn't work correctly with middlewares (notably with cookies), do you have the same issue when running the code locally?

To reproduce:
1. fork this https://github.com/QuiiBz/next-international
2. git clone forked repository
3. cd examples
4. cd next-app
5. pnpm i

![image](https://github.com/QuiiBz/next-international/assets/39565703/527c11a5-7884-42d6-b39b-503f9f3065e0)

I tried to fix it with `pnpm i next-international/middleware` but got this
```
 pnpm i next-international/middleware
 ERROR  Command failed with exit code 128: git ls-remote git+ssh://git@github.com/next-international/middleware.git HEAD
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

This error happened while installing a direct dependency of /home/kali/Documents/GitHub/mvp-without-repo-internatiolization/fork-next-international/examples/next-app

pnpm: Command failed with exit code 128: git ls-remote git+ssh://git@github.com/next-international/middleware.git HEAD
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
    at makeError (/usr/local/lib/node_modules/pnpm/dist/pnpm.cjs:24966:17)
    at handlePromise (/usr/local/lib/node_modules/pnpm/dist/pnpm.cjs:25537:33)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getRepoRefs (/usr/local/lib/node_modules/pnpm/dist/pnpm.cjs:110687:23)
    at async resolveRef (/usr/local/lib/node_modules/pnpm/dist/pnpm.cjs:110699:20)
    at async resolveGit (/usr/local/lib/node_modules/pnpm/dist/pnpm.cjs:110650:24)
    at async Object.resolve (/usr/local/lib/node_modules/pnpm/dist/pnpm.cjs:110949:173)
    at async run (/usr/local/lib/node_modules/pnpm/dist/pnpm.cjs:123088:23)
../..                                    | Pr
```

**Comment by QuiiBz** [comment]
This is a separate issue, you have to build the packages locally since you're forking the repo. See the contributing guide: https://github.com/QuiiBz/next-international/blob/main/CONTRIBUTING.md

**Comment by pj258** [comment]
Hi. I'm stuck with the error **Argument of type 'string' cannot be assigned to the parameter of type 'never'** on server components only, even on a demo example. Maybe a problem with the local environment. 
Can't get around it. But language switching works fine.

![image](https://github.com/user-attachments/assets/62461417-2661-4764-a1f8-6f6d3e2205ff)
