### ISSUE TITLE
defaultLocale not working

### ISSUE THREAD

**Issue by sajjadramezani73** [QuiiBz/next-international#373]
hi
I have used this package in the next 13.4 app router project

config for i18n with persian and english language and defaulLocale equal fa
const I18nMiddleware = createI18nMiddleware({
  locales: ['en', 'fa'],
  defaultLocale: 'fa',
  urlMappingStrategy: 'rewriteDefault',
})

why after the implementation of the project
localhost:4200/en it opens?

**Comment by QuiiBz** [comment]
What does your `Accept-Language` header looks like in the initial request? You might want to usethe `resolveLocaleFromRequest` option in the middleware to manually override the logic.

**Comment by sajjadramezani73** [comment]
thank you
My problem is solved
