### ISSUE TITLE
Arguments for the rest parameter 'params' were not provided.

### ISSUE THREAD

**Issue by SaddamMohsen** [QuiiBz/next-international#374]
**Describe the bug**
when i call the translation in client or server it show error and require another param named count 
while the file of translation does not contain any parameters
![image](https://github.com/QuiiBz/next-international/assets/55493475/dd86cdbf-6080-494c-9ad0-b5e876185928)
and this is image of translation files
![image](https://github.com/QuiiBz/next-international/assets/55493475/20258e7b-cdb8-4f79-9ab6-8ebab4aaf5de)

so how to solve this problem

**About (please complete the following information):**
 - next-international version "^1.2.4",
 - Next.js version ^14.1.1-canary.82

*

**Comment by paulgrieselhuber** [comment]
Running into this as well, same version, nearly identical implementation.

**Comment by SaddamMohsen** [comment]
> Running into this as well, same version, nearly identical implementation.

sorry it was error in the translation file 
i have been solve it 
thank you
