### ISSUE TITLE
Object spreading locales breaks variable inference

### ISSUE THREAD

**Issue by NuroDev** [QuiiBz/next-international#38]
In an effort to make my locale structure cleaner I have begun splitting it into multiple files / objects that I can import & object spread in the locale index default export.

However there currently seems to be a bug whereby object spreading breaks the variable type inference.

I've created a CodeSandbox to [demonstrate the issue](https://codesandbox.io/s/next-international-object-spreading-54k8yt?file=/pages/index.tsx)

I feel like this may be more of a lower level TypeScript template inference issue but thought I would report it anyway 🙂

**Comment by QuiiBz** [comment]
Interesting use case! Looking at the type of the locale, the spread object keys are `string`:

<img width="477" alt="Screenshot 2022-10-03 at 15 47 55" src="https://user-images.githubusercontent.com/43268759/193593714-db913869-371a-4efd-a168-87bd11bb319b.png">

You'll need to add an `as const` to the object to narrow the values, and such get proper params extraction:

<img width="320" alt="Screenshot 2022-10-03 at 15 50 06" src="https://user-images.githubusercontent.com/43268759/193594211-abe1d8fc-9ca1-4737-ae90-140b2967da88.png">

<img width="558" alt="Screenshot 2022-10-03 at 15 49 30" src="https://user-images.githubusercontent.com/43268759/193594078-b5581cc3-9a2d-49a9-aa36-3a98852209cc.png">

Let me know if that fixed the issue!

**Comment by NuroDev** [comment]
Yup, that seems to have fixed it.
Good to know how to fix this, thanks 😄
