### ISSUE TITLE
What should be the locale type

### ISSUE THREAD

**Issue by addlistener** [QuiiBz/next-international#381]
What should be the locale type here? 

```
// pages/_app.tsx
import { I18nProvider } from '../locales'
import { AppProps } from 'next/app'
 
export default function App({ Component, pageProps }: AppProps) {
  return (
    <I18nProvider locale={pageProps.locale}>
      <Component {...pageProps} />
    </I18nProvider>
  )
}
```

I tried using `typeof en` but there's type mismatch. Even though all the locales are the same. 
```
// locales/en.ts
export default {
  "product slogan": "xxxx",

  "dash": {
    "leftnav": {
      "sites": "xxxx",
      "account": "xxxx"
    }
  }
} as const
```

I don't know it's `FlattenLocale` or `as const`. Still thinking...

The deducted type
<img width="1031" alt="image" src="https://github.com/QuiiBz/next-international/assets/4531670/354e672f-e5bf-40ec-b68e-bbdb1221a076">

My type
<img width="858" alt="image" src="https://github.com/QuiiBz/next-international/assets/4531670/80a0096c-e678-4203-aeec-c3bb8795b865">

**Comment by QuiiBz** [comment]
It's a complex type: to avoid manually writing it, you can do:

```
```

**Comment by addlistener** [comment]
Thank you! It would be great this could be included in the official examples
