### ISSUE TITLE
Complex inference is making editors go haywire, @ts-nocheck does not resolve this.

### ISSUE THREAD

**Issue by SanderCokart** [QuiiBz/next-international#388]
# Description

With app router and client.ts, exporting `useI18n, useScopedI18n, useChangeLocale, defineLocale` resutls in the following error:

```
TS2742: The inferred type of useChangeLocale cannot be named without a reference to
../../node_modules/next-international/dist/types-wFm7okgu
. This is likely not portable. A type annotation is necessary.
```

A similar error pops up for `getI18n, getScopedI18n` in server.ts.

# Reproduce
Here is my client.ts
```ts
'use client';

import { createI18nClient } from 'next-international/client';

export const { useI18n, useScopedI18n, useChangeLocale, defineLocale, useCurrentLocale, I18nProviderClient } =
  createI18nClient({
    en: () => import('./en'),
    nl: () => import('./nl'),
  });
```

here is my server.ts
```ts
// @ts-nocheck
import { createI18nServer } from 'next-international/server';

const { getI18n, getScopedI18n, getStaticParams, getCurrentLocale } = createI18nServer({
  en: () => import('./en'),
  nl: () => import('./nl'),
});

export { getI18n, getScopedI18n, getStaticParams };
```

# Expectation
No typescript errors.

# Screenshots
![image](https://github.com/QuiiBz/next-international/assets/45256817/b46c88b5-8d5b-4dd3-b0ea-f943dfe3c40e)

# About
 - next-international version: `^1.2.4`
 - Next.js version: `^14.1.4`

# Additional context
I am aware V2 is underway and hope it resolves many of these issues but with @ts-ignore and @ts-nocheck not working it will trigger some OCD developers.

**Comment by iStorry** [comment]
> This is related to monorepos, not `next-international`.

Did you managed to fix it?

**Comment by MohammadKurjieh** [comment]
@iStorry a temporary fix would be adding the following to that file.
`import type {} from 'next-international';`

Also note, as @SanderCokart mentioned the cause of the error is not `next-international`. 
Ref: https://github.com/microsoft/TypeScript/issues/47663
Original Solution Source: https://github.com/microsoft/TypeScript/issues/47663#issuecomment-1270716220

**Comment by julianklumpers** [comment]
The `import type {} from 'next-international';` did only fix 2 out of 3 errors for me, the `useChangeLocale` still had the reference error.

The solution for me was the explicitly specify the path in my `tsconfig.json` like this:

```json
{
  "extends": "@repo/ts-config/nextjs.json",
  "compilerOptions": {
    "paths": {
      "next-international/*": ["../../node_modules/next-international/*"]
    },
    "baseUrl": "."
  },
  "include": ["**/*.ts"],
  "exclude": ["dist", "build", "node_modules"]
}

```

**Comment by lumpinif** [comment]
> The `import type {} from 'next-international';` did only fix 2 out of 3 errors for me, the `useChangeLocale` still had the reference error.
> 
> The solution for me was the explicitly specify the path in my `tsconfig.json` like this:
> 
> ```json
> {
>   "extends": "@repo/ts-config/nextjs.json",
>   "compilerOptions": {
>     "paths": {
>       "next-international/*": ["../../node_modules/next-international/*"]
>     },
>     "baseUrl": "."
>   },
>   "include": ["**/*.ts"],
>   "exclude": ["dist", "build", "node_modules"]
> }
> ```

this works for me.
