### ISSUE TITLE
Failed to execute 'removeChild' on 'Node' when using `useChangeLocale` and `useCurrentLocale`

### ISSUE THREAD

**Issue by ARiyou2000** [QuiiBz/next-international#401]
**Describe the bug**
before using `useChangeLocale` and `useCurrentLocale` everything is fine. but after using these hooks, I will get the following error:

> NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

**To Reproduce**
```ts
"use client";

import { createI18nClient } from "next-international/client";

import { supportedLangs } from "@/types/supportedLangs";

export const {
  useI18n,
  useScopedI18n,
  useChangeLocale,
  useCurrentLocale,
  I18nProviderClient,
} = createI18nClient<Record<supportedLangs, () => Promise<any>>>({
  en: () => import("../../dictionaries/en"),
  fa: () => import("../../dictionaries/fa"),
});

const LanguageSelect = (props: SelectProps) => {
  const currentLocale = useCurrentLocale();
  const changeLocal = useChangeLocale();

  return (
    <div key={"langDiv"}>
      <Select
        key={"langSelect"}
        value={currentLocale}
        onValueChange={changeLocal}
        {...props}>
        <SelectTrigger className="w-[180px]">
          <SelectValue placeholder="lang" />
        </SelectTrigger>
        <SelectContent>
          <SelectItem value="fa">Fa</SelectItem>
          <SelectItem value="ru">RU</SelectItem>
          <SelectItem value="en">English</SelectItem>
        </SelectContent>
      </Select>
    </div>
  );
};
```

**Expected behavior**
I should get result and not error

**Screenshots**
![Screenshot from 2024-05-11 09-44-09](https://github.com/QuiiBz/next-international/assets/35896230/b24198ec-c235-4029-bba3-a3de867b4d5b)

**About (please complete the following information):**
 - "next": "14.2.3",
 - "next-auth": "^4.24.7",
 - "next-international": "^1.2.4",

**Comment by sara0405** [comment]
I'm having the same problem. Did you figure it out in the meantime?

**Comment by Farzin-Firoozi** [comment]
+1

**Comment by ARiyou2000** [comment]
### Update:

I believe the root of problem is the mismatch between next-internationals param name and the name i used. As docs suggest:

> Move all your routes inside an `app/[locale]/` folder

While I was using `app/[lang]/` and for this reason it couldn't get param with the name of `locale`.

I'm closing this issue.
