### ISSUE TITLE
 i18n support is not compatible with next export

### ISSUE THREAD

**Issue by chaosLegacy** [QuiiBz/next-international#41]
When running next export 
I get the following error 

Error: i18n support is not compatible with next export. See here for more info on deploying: https://nextjs.org/docs/deployment

I found this tutorial: https://dev.to/adrai/static-html-export-with-i18n-compatibility-in-nextjs-8cd 
the solution was provided from next-i18next, wan we use the same approach for next-international?

Since I couldn't fine anything in the README nor inside the closed issues , do you recommend following this solution or is there an alternative way for next-international?

**Comment by QuiiBz** [comment]
Yes, this is an issue with Next.js :( You have two options:

1) Use SSR instead of SSG, but that means you need a server to SSR your app:*

```typescript
export const getServerSideProps = getLocaleProps()

// or with an existing `getServerSideProps` function:
export const getServerSideProps = getLocaleProps((ctx) => {
  // your existing code
  return {
    ...
  }
})
```

2) [Load initial locale client-side](https://github.com/QuiiBz/next-international#load-initial-locales-client-side)

Maybe with the upcoming Next.js Layout, we'll be able to use SSG with i18n, but for now, this is the only available option I'm aware of.

**Comment by chaosLegacy** [comment]
Hello @QuiiBz hope you're having a wonderful day, thank you so much for your quick feedback
I'm already using the second option you mentioned [Load initial locale client-side](https://github.com/QuiiBz/next-international#load-initial-locales-client-side)
And i removed getLocaleProps from all my pages, I wrapped my _app.tsx with I18nProvider like you explained in the README file
But I still get the  i18n support is not compatible with next export

**Comment by QuiiBz** [comment]
Yeah, Next.js doesn't allow the `i18n` key inside `next.config.js` with static exports :( . Maybe it will be fixed with the upcoming layout feature of Next.js 13, which should be announced tomorrow.

**Comment by QuiiBz** [comment]
Quick update: next-international should work with static exports using the app directory in Next 13: #42

**Comment by QuiiBz** [comment]
Closing as support for Next.js App Router has landed in https://github.com/QuiiBz/next-international/releases/tag/0.5.0
