### ISSUE TITLE
Package incompatible with Next.JS 13 `/app` directory

### ISSUE THREAD

**Issue by saphewilliam** [QuiiBz/next-international#42]
Since Next.JS's new `/app` directory [moves away from built-in i18n support](https://beta.nextjs.org/docs/app-directory-roadmap#not-planned-features) and instead advises to use `generateStaticParams` and middleware in the `app` directory, are you planning on adding such a middleware solution to this package? Currently the usage of `useRouter` crashes the `I18nProvder` in the new version of Next.JS

**Comment by QuiiBz** [comment]
Yeah, this library isn't compatible with Next.js 13 inside the app directory. I haven't yet got the time to look into how to properly support it, but it's definitely something that I want to have in the future.

**Comment by saphewilliam** [comment]
Awesome to hear! Let me know if I can be of any kind of help with implementation 😃

**Comment by noxify** [comment]
Hey @QuiiBz - it seems NextJS has updated their docs about i18n.

https://beta.nextjs.org/docs/guides/internationalization

They added also some examples - Maybe a good startpoint to make the package Next13 ready?

**Comment by QuiiBz** [comment]
Thanks for the heads-up! I'll take a look at it this weekend.

**Comment by Sn0wye** [comment]
Hey @saphewilliam, is it still incompatible? In case so, have you found any solution?

**Comment by QuiiBz** [comment]
I've just published `next-international@0.5.0` with initial support for the App Router: https://github.com/QuiiBz/next-international/releases/tag/0.5.0

[See the documentation here](https://github.com/QuiiBz/next-international/tree/main#app-router)

I'm closing this issue but feel free to open new ones if you find bugs in this new implementation.
