### ISSUE TITLE
In v1.3.0, ReturnType of getCurrentLocale() must be Promise

### ISSUE THREAD

**Issue by you0518** [QuiiBz/next-international#428]
**Describe the bug**

getLocaleCache now returns Promise, so the ReturnType of getCurrentLocale must be Promise

https://github.com/QuiiBz/next-international/blob/c3326333145415a99bda35963cf61044352e9c88/packages/next-international/src/app/server/create-get-current-locale.ts#L5

```ts
return getLocaleCache() as Promise<LocalesKeys>;
```

**To Reproduce**

**Expected behavior**
getCurrentLocale returns Promise.

**Screenshots**

**About (please complete the following information):**
 - next-international version [e.g. 0.9.5]
 - Next.js version [e.g. 13.4.0]

**Additional context**

**Comment by aurorascharff** [comment]
+1 experiencing this bug in v1.3.0. Fixed it for my app by awaiting getCurrentLocale (even though typescript says its not a promise).

**Comment by QuiiBz** [comment]
Fixed in https://github.com/QuiiBz/next-international/pull/431, released in [version 1.3.1](https://github.com/QuiiBz/next-international/releases/tag/1.3.1).
