### ISSUE TITLE
[BUG] Interpolation with variables does not work

### ISSUE THREAD

**Issue by damianricobelli** [QuiiBz/next-international#44]
I have been testing interpolation with translations of this style: `"{count, plural, =1 {adult} other {adults}}"`

But I don't really see that it's working. It always throws "other".

**Comment by damianricobelli** [comment]
@QuiiBz has this been solved with the new version?

**Comment by QuiiBz** [comment]
@damianricobelli it now only returns `count`, because plural isn't supported in the backend either as it would increase the bundle size a lot. I'm thinking of making it supported optionally.

**Comment by QuiiBz** [comment]
I've released [version 0.7.0](https://github.com/QuiiBz/next-international/releases/tag/0.7.0) which now includes support for plural translations! See the documentation here: https://github.com/QuiiBz/next-international#plurals
