### ISSUE TITLE
Force consistency between all locale files

### ISSUE THREAD

**Issue by baptisteArno** [QuiiBz/next-international#51]
I think it's a good practice would be to have a single source of truth locale file like `en.ts` and having the other files be based on it:

```ts
// en.ts
export default  {
    key: 'value',
} as const
```

```ts
// fr.ts
import type Locale from './en'

export default {
    key: "value"
} satisfies Record<keyof typeof Locale, string>
```

Anything wrong with that? Would it be worth mentioning in the README?

**Comment by QuiiBz** [comment]
This is currently done using `defineLocale`, but `satisfies` also works fine! Not sure which one is easier for users 🤔 

With TypeScript 5.0 and the [const type parameter](https://devblogs.microsoft.com/typescript/announcing-typescript-5-0-rc/#const-type-parameters) I think we'll even be able to remove the `as const`!

**Comment by baptisteArno** [comment]
Oh, that's great, didn't see that in the README 🤘
