### ISSUE TITLE
SSR Not working

### ISSUE THREAD

**Issue by Royal-lobster** [QuiiBz/next-international#56]
Trying to integrate locales with SSR, but i am unable to get it to working. Any thing wrapped under I18nProvider is loosing SSR. 

# Reproduction
- Go to https://stackblitz.com/edit/next-typescript-veg8jj
- View the output in new tab (https://nexttypescriptveg8jj-hxit--3000--d830b1a2.local-credentialless.webcontainer.io)
- inspect source to verify the "Hello" missing from source

**Comment by QuiiBz** [comment]
You should move the `export const getStaticProps = getLocaleProps()` to each page, not from the `_app.tsx`

**Comment by Royal-lobster** [comment]
Thanks a lot !! That works !
