### ISSUE TITLE
Default Locale Redirection not Working

### ISSUE THREAD

**Issue by bim-oulabi** [QuiiBz/next-international#68]
For some reason this code still redirects to /en instead of /ar in first visit ( regardless what I insert as default locale )

```javascript
import { createI18nMiddleware } from 'next-international/middleware';
import { NextRequest } from 'next/server';

const I18nMiddleware = createI18nMiddleware(['ar', 'en'] as const, 'ar');

export function middleware(request: NextRequest) {
    return I18nMiddleware(request);
}

export const config = {
    matcher: ['/((?!_next).*)'],
};
```

**Comment by bim-oulabi** [comment]
in addition to having support for detect language maybe?
and thank you for the awesome lib, so far everything else has been working flawlessly in server components + client components,
without having to drill props nor complicated setup

**Comment by QuiiBz** [comment]
Thanks for the kind words! I'll take a look at this issue.

**Comment by QuiiBz** [comment]
The default locale serves as a fallback if the no locale matches the `Accept-Language` header. Your browser might be configured to use English as the default locale, so next-international tries as much as possible to use the user's locale.

**Comment by bim-oulabi** [comment]
Wouldn't make more since if we can pass an argument ( which I thought the second param in the middleware is for ) to force default language? if its none existing we can use accept-language in this case

**Comment by QuiiBz** [comment]
I don't think it's a good idea to force a specific language if users specifically set their preferred language. This goes against what the user expects.

I'm curious about what the community thinks about this. Feel free to add reactions if you agree/disagree to see what we should do in the future.

**Comment by bim-oulabi** [comment]
Well this is exactly why its only for default because some systems may focus on having a specific default language.

in case the user preferred language isn't supported how would it behave though? would it choose the default passed as default locale?

**Comment by QuiiBz** [comment]
> in case the user preferred language isn't supported how would it behave though? would it choose the default passed as default locale?

Yes, if the preferred language isn't configured in your app, it will use configured one (2nd argument)

**Comment by bim-oulabi** [comment]
Perfect
Thank you ao much🙏🙏🙏
