### ISSUE TITLE
Discussion: support for JSON modules

### ISSUE THREAD

**Issue by jasperverbeet** [QuiiBz/next-international#85]
Finally, a strongly typed i18n package! Thank you.

In my experience, most i18n translations are stored in JSON format. This facilitates easy translation by external services and enables tools like [i18n-ally](https://github.com/lokalise/i18n-ally) to enhance the translation experience. Comparatively, Typescript files pose more management challenges.

While Typescript natively supports importing JSON modules, it falls short of a feature equivalent to const assertion, thereby compromising some part of its type safety. In the Typescript repository, you can refer to [this issue](https://github.com/microsoft/TypeScript/issues/32063) for more insights.

Here's an example:

```ts
// en.ts
export default {
  hello: '{world}'
} as const;

// i18n.ts
import en from 'en';

assertType<{
  readonly hello: '{world}';
}>(en); // true
```
vs.

```ts
// en.json
{
  "hello": "{world}"
}

// i18n.ts
import en from 'en.json';

assertType<{
  hello: string;
}>(en);
```

This, in turn, causes Typescript to be unable to infer template arguments for the JSON object. So the following will work when dealing with native typescript, but not with JSON modules.

```ts
// Won't work with JSON modules because `{world}` could not be inferred from the type `string.`
t('hello', {
  world: 'Mars'
})
```

A potential solution to this problem (if you want to call it that) could be to type the second argument as:

```ts
type ParamsObject = {
  world: LocaleValue;
  // Accept any key
  [key: string]: LocaleValue;
}

const example = {
  world: 'Mars',
  nonExistingPram: 'Moon'
} satisfies ParamsObject
```

This approach ensures you don't compromise type safety when dealing with native Typescript while supporting JSON modules.

Please let me know what your thoughts are.

**Comment by jasperverbeet** [comment]
I just read this issue: https://github.com/QuiiBz/next-international/issues/28, which would also be a good direction for a solution.

**Comment by QuiiBz** [comment]
This is indeed a complex problem. We'll always recommend using TypeScript files for translations because it's the easiest way for developers to build their apps while providing the assurance that it will work as expected at runtime.

I18n management softwares like [Localazy](https://localazy.com/) supports well TypeScript translations, but as you said, this is sadly not the case for all of them. If you use JSON translations, someone will have to maintain a separate `type` that includes every key and translation with params. This is not documented but supported by next-international, see the 2nd part of this comment: https://github.com/QuiiBz/next-international/pull/52#issuecomment-1500324926

Could that solve your issue, or should we investigate more into #28?

**Comment by jasperverbeet** [comment]
Yeah, this is a good enough solution for JSON support. I agree that native Typescript is better for most people. We can use tools like Deepl and even ChatGPT to translate the files >90% for free. I'll comment on the other thread with my thoughts there.

**Comment by roux1max** [comment]
Hi!

Thanks for the great work on this package. Just wanted to share a little tip I found to infer JSON types. I just wrapped the `useI18n()` with the following wrapper:

```typescript
const dictionaries = {
    'fr': () => import('./dictionaries/fr.json'),
    'en': () => import('./dictionaries/en.json'),
};

// This part is just code extracted from the package that I used locally so that I could infer types the same way the package does.
export type Locale = FlattenLocale<GetLocaleType<typeof dictionaries>>;
export type LocaleKey<Scope extends Scopes<Locale> | undefined = undefined> = LocaleKeys<Locale, Scope>;

export const useI18nTyped = () => {
    const t = useI18n();

    return t<LocaleKey>;
};
```

Seems to me that if we would simply call `createT()` with the `Locale` type parameter explicitly it would work with JSON out of the box.

Let me know if it helps!

**Comment by QuiiBz** [comment]
Closing as we have a documentation page since a few weeks about how to support JSON translations while retaining type-safety: https://next-international.vercel.app/docs/writing-locales#json
