### ISSUE TITLE
useChangeLocale does not support searchParams

### ISSUE THREAD

**Issue by malkavi6** [QuiiBz/next-international#92]
useChangeLocale removes searchParams from the url.
Version tested: 0.8.0

**Comment by QuiiBz** [comment]
Thanks, I released 0.8.1 which contains #93

**Comment by slowwriter** [comment]
Storing searchParams after changing the language by useChangeLocale stopped working.
I implemented all the changes from the [release 1.0.0](https://github.com/QuiiBz/next-international/releases/1.0.0) description.


Next: 13.5.3
next-international: 1.0.1
